require("dotenv").config();

const db = require("../config/db");
const { sql } = require("slonik");
const seed = async () => {
	try {
		await db.query(sql`
    		INSERT INTO venues (venue_name, venue_address, indoor_facilities, outdoor_facilities)
			VALUES ('CDM Gimnasio Moscardó ', 'C/ Pilar de Zaragoza, 93 ', '2 pabellones. 2 piscinas (Elola: vaso de 25 m. y Samaranch: vaso de 25 m). Sala de musculación. Sala multiusos. Sala de ciclo sala. Sala de fisioterapia. Unidad de reconocimientos médicos ', 'Pista de tenis. Pista de pádel de cristal. 2 tenis de mesa'),
			('CDM SAN BLAS ', 'C/ Arcos de Jalón, 59 ', '3 pabellones (pabellón “Antonio Mata”, pabellón de gimnasia artística y pabellón circular). Piscina (vaso de 25 m.). Sala de musculación. Sala multiusos. Sala de artes marciales. Sala de psicomotricidad ', 'Piscina (vaso de 50 m., 2 vasos de recreo y vaso infantil). 4 pistas polideportivas. 4 pistas de pádel de cristal. 3 tenis de mesa'),
			('CDM Aluche ', 'Avda. de las Águilas, 14 ', 'Pabellón circular. Pabellón de artes marciales (sala de musculación, sala multiusos, 2 saunas y sala de artes marciales). Piscina (vaso de 50 m. y vaso de 25 m.) Unidad de reconocimientos médicos ', 'Piscina (gemelas y vaso infantil). Pista de atletismo. Campo de fútbol 11 de césped artificial. 9 pistas polideportivas. Pista de patinaje y hockey con cubierta. 2 pistas de vóley playa. 9 pistas de tenis. 2 frontones cortos 4 pistas de pádel. Patinódromo. 19 tenis de mesa. Circuito de seguridad vial'),
			('CDM Hortaleza ', 'Ctra. de la Estación de Hortaleza, 11', 'Pabellón Piscina (vaso de 25 m.) Sala de musculación. Sala multiusos. 4 pistas de pádel', 'Piscina (2 vasos de 50 m. y vaso infantil). Campo de fútbol 11. Pista polideportiva. 2 pistas de tenis'),
			('CDM El Olivillo ', 'C/ Olivillo, 4', 'Pabellón polideportivo', '-'),
			('CDM Ciudad de los Poetas ', 'C/ Antonio Machado, 12 ', 'Pabellón polideportivo ', '-'),
			('CDM Ángel Nieto–ant. Puente de Vallecas', 'C/ Payaso Fofó, 7 ', 'Pabellón polideportivo. Piscina (1 vaso de 25 metros y vaso de enseñanza). Sala de musculación. Sala multiusos. Sala de artes marciales. 4 pistas de squash. ', '-'),
			('CDM Pabellón Villa de Madrid ', 'C/ Los Brezos, 6', 'Pabellón y sala de armas de esgrima', '-'),
			('CDM Peñagrande ', 'Avda. Monforte de Lemos, 184', 'Pabellón. 2 piscinas. Sala de musculación. 5 salas multiusos. Sauna. Spa', 'Piscina de verano. 4 pistas de tenis. 6 pistas de pádel. Circuito de footing'),
			('CDM Chamartín ', 'Avda. Pío XII, 2 ', 'Pabellón. Piscina (un vaso de 25 metros y otro vaso de 22,5 metros y solárium). Playa exterior de piscina-solárium. 2 salas de musculación. 4 salas multiusos. Sala de fisioterapia. Zona termal', '-'),
			('CDM Vallehermoso ', 'Avda. Islas Filipinas, 7 ', 'Pabellón. Piscina (vaso de 25 m y vaso de enseñanza). Sala de musculación. 5 salas multiusos. Sala de fisioterapia. Sauna (con baño de vapor). Spa ', 'Piscina (vaso de 25 m.) 3 pistas de pádel. Spa'),
			('CDM Concepción ', 'C/ José del Hierro, 5', 'Pabellón. Piscina (vaso de 25 m). Sala de musculación. Unidad de reconocimientos médicos ', 'Piscina (vaso de 25 m. y vaso infantil). Campo de fútbol 11 de césped artificial. Pista de atletismo (3 calles). 2 pistas polideportivas. Pista de patinaje. 4 pistas de tenis. 2 pistas de pádel. 2 frontones cortos. 3 tenis de mesa'),
			('CDM Marques de Samaranch', 'Pº. Imperial, 20', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza y solárium). Sala de musculación. 2 salas multiusos. Sala de fisioterapia. 2 saunas. Sala de psicomotricidad. Unidad de reconocimientos médico', 'Fútbol 11 de césped artificial y 4 pistas de pádel'),
			('CDM Margot Moles–ant. Vicálvaro', 'Pº. del Polideportivo, 3', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza)', 'Piscina (vaso de 50 m. y vaso infantil). Pista de atletismo. Campo de fútbol 11 de césped artificial. 2 campos de fútbol 7 de césped artificial. 2 pistas polideportivas. 3 pistas de tenis. 4 pistas de pádel. 4 tenis de mesa.'),
			('CDM Centro Integrado Arganzuela ', 'C/ Canarias, 17', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). 2 salas de musculación. Sala multiusos y sala de fisioterapia', '4 pistas de pádel'),
			('CDM Raúl González', 'Parque Benimamet, 137', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). 2 salas multiusos', '-'),
			('CDM Antonio Díaz Miguel ', 'C/ Joaquín Dicenta, 1', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 2 sala multiusos. Sala de ciclo-Sala. ', '-'),
			('CDM Faustina Valladolid–ant. Valdebernardo', 'c/ Ladera de los Almendros, 2 ', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 2 salas multiusos. 2 pistas de esgrima. ', 'Campo de fútbol 11 de césped artificial. 2 campos de fútbol 7 de césped artificial. 9 pistas de tenis 10 pistas de pádel.'),
			('CDM Alfredo Goyeneche ', 'C/ Arroyo de Pozuelo, 99 ', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 2 salas multiusos. 2 saunas ', '2 pistas de tenis. 5 pistas de pádel (3 de ellas de cristal). Rocódromo'),
			('CDM Entrevías ', 'C/ Ronda del Sur, 4', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 2 salas multiusos. Pista polideportiva', 'Piscina (vaso de 50 m. y vaso infantil). Campo de fútbol 11 de césped artificial. 2 pistas de tenis. 2 pistas de pádel'),
			('CDM Daoiz y Velarde ', 'Avda. Ciudad de Barcelona, 162 ', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 2 salas multiusos. Sala de fisioterapia. 2 saunas. Sala de psicomotricidad. Unidad de reconocimientos médicos ', 'Pista de pádel de cristal'),
			('CDM Barajas ', 'Avda. de Logroño, 70 ', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 2 salas multiusos. Sala de psicomotricidad ', '4 pistas de tenis. 4 pistas de pádel'),
			('CDM Pradillo ', 'C/ Pradillo, 33', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 3 salas multiusos. Sala de ciclo sala. Sala Fisioterapia e hidroterapia. 2 saunas. Unidad de reconocimientos médico', 'Campo de fútbol 7 de césped artificial. 2 pistas polideportivas. Pista de tenis. 6 pistas de pádel'),
			('CDM Wilfred Agbonavbare–ant. Alberto García', 'C/ Reguera de Tomateros, 39', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. Sala multiusos', 'Campo de fútbol 11 de césped artificial. Campo de fútbol 7 de césped artificial. Pista polideportiva. Pista de fútbol sala. Pista de baloncesto. Pista de hockey patines. 2 pistas de tenis. 4 pistas de pádel de cristal. Campo de fútbol 11 de césped artificial – (Ronda del Sur 231)'),
			('CDM La Mina ', 'C/ Monseñor Óscar Romero, 41 ', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. Sala multiusos. 4 pistas de squash ', 'Piscina (vaso de 50 m., vaso de recreo y vaso infantil). Frontón corto. Pista polideportiva. 2 pistas de pádel. Campo de fútbol La Mina. (C/ Monseñor Óscar Romero, 37)'),
			('CDM La Masó ', 'C/ La Masó, 80 c/v Avda. Ventisquero de la Condesa', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. Sala multiusos. Sala de Fisioterapia e hidroterapia. 2 sauna', 'Campo de fútbol 11 de césped artificial. Rocódromo'),
			('CDM Cerro Almodóvar ', 'C/ Cerro de Almodóvar, 9. ', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. Sala multiusos. Sala de psicomotricidad. Sala de halterofilia. ', 'Piscina (1 vaso de recreo profundo, 1 vaso de recreo normal y vaso infantil). 2 pistas polideportivas. Frontón corto. 2 Tenis de mesa'),
			('CDM Plata y Castañar', 'Pº. Plata y Castañar, 7 y 9. ', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala multiusos. Sala de fisioterapia. Unidad de reconocimientos médicos ', 'Piscina (vaso de 50 m., vaso de recreo y vaso infantil). Campo de fútbol 11 de césped artificial. Campo de fútbol 7 de césped artificial. Pista polideportiva. Pista de baloncesto. Pista de patinaje con cubierta. 6 pistas de tenis. 4 pistas de pádel'),
			('CDM Palomeras ', 'C/ Tranvía de Arganda, 4 ', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala musculación. 2 salas polivalentes. Sala de artes marciales. Sala de esgrima. Sala de psicomotricidad. Unidad de reconocimientos médicos ', 'Piscina (vaso de 50 m, 2 vasos de recreo y un vaso infantil). Pista de Atletismo. 2 campos de fútbol 11 de césped artificial. 6 pistas polideportivas. 5 pistas de tenis. Frontón corto. 4 pistas de pádel techadas. 2 tenis de mesa'),
			('CDM Moratalaz ', 'C/ Valdebernardo, 2 ', 'Pabellón. Piscina (vaso de 25 m.) Sala de musculación. 2 salas multiusos. Sala de artes marciales. Sala de psicomotricidad. Unidad de reconocimientos médicos ', 'Piscina (3 vasos de 50 m. y vaso infantil). Pista de Atletismo. Campo de fútbol 11 de césped artificial. 3 pistas de fútbol sala. Pista de baloncesto. Pista de patinaje. Pista de vóley playa. 6 pistas de tenis. 2 frontones largos. 4 pistas de pádel de cristal. Campo de tiro con arco'),
			('CDM Orcasur ', 'C/ Moreja, 11', 'Pabellón. Piscina (vaso de 25 m.) Sala de musculación. Sala multiuso', '2 campos de fútbol 7 de césped artificial. Pista de fútbol sala. Pista de tenis. Frontón largo. 2 pistas de pádel. 4 tenis de mesa (inoperativas)'),
			('CDM Fernando Martín ', 'Avda. Santo Ángel de la Guarda, 6', 'Pabellón. Piscina (vaso de 25 m.) Sala de musculación. Sala multiusos', 'Pista Polideportiva y 2 pistas de tenis'),
			('CDM Triángulo de Oro ', 'C/ Bravo Murillo, 376 ', 'Pabellón. Piscina (vaso de 25 m.). Sala de musculación. 2 salas multiusos. Frontón cubierto', ' - '),
			('CDM José María Cagigal ', 'C/ Santa Pola, 22', 'Pabellón. Piscina (vaso de 25 m.). Sala de musculación. 2 salas multiusos. Sala de psicomotricidad. Fisioterapia e hidroterapia. 2 saunas. Unidad de reconocimientos médico', 'Piscina (vaso de 50 m., vaso de recreo e infantil). 5 pistas de tenis'),
			('CDM Vicente del Bosque ', 'Avda. Monforte de Lemos, 13 ', 'Pabellón. Piscina (vaso de 25 m.). Sala de musculación. Sala de artes marciales. Unidad de reconocimientos médicos ', 'Piscina (2 vasos de 50 m. y vaso infantil). Campo de fútbol de césped artificial. 2 pistas polideportivas. 2 pistas de baloncesto. 6 pistas de tenis. 6 pistas de pádel (2 de ellas de cristal). Pista de vóley playa. Pista de patinaje. 2 tenis de mesa. Zona nudista.'),
			('CDM Francisco Fernández Ochoa ', 'C/ Catorce Olivas, 1', 'Pabellón. Piscina (vaso de 50 m. y vaso de enseñanza). Sala de musculación. 3 salas multiusos, sauna. Spa', '2 campos de fútbol 7 de césped artificial. 8 pistas de pádel. 6 pistas de tenis. Pista de Hockey patines y patinaje.'),
			('CDM Miguel Guillén Prim ', 'C/ Fuentidueña, 6', 'Pabellón. Sala de musculación', 'Campo de fútbol 7 de césped artificial'),
			('CDM La Elipa ', 'C/ Alcalde Garrido Juaristi, 17', 'Pabellón. Sala de musculación. 2 salas multiusos. Frontón. Rocódromo', 'Piscina (vaso de 50 m., vaso de recreo y vaso infantil). 2 campos de fútbol 11 de césped artificial. 2 campos de fútbol 7 de césped artificial. Pista polideportiva cubierta. 1 campo de béisbol. 10 pistas de tenis. 6 pistas de pádel 2 de cristal, 7 mesas de tenis mesa. 1 circuito de automodelismo. 3 túneles de bateo. Zona nudista.'),
			('CDM Pepu Hernández ', 'Avda. de Niza, 8', 'Pabellón. Sala de musculación. 5 salas multiusos. 2 saunas. Sala de fisioterapia', 'Campo de fútbol 11 de césped artificial (señalizado para fútbol 7). 3 pistas de tenis 4 pistas de pádel'),
			('CDM Félix Rubio', 'C/ Alianza, 2 ', 'Pabellón. Sala de musculación/cardio. Rocódromo', 'Campo de fútbol 11 de césped artificial. Campo de fútbol 5 x 5 de césped artificial. Pista polideportiva. 2 pistas de baloncesto 3x3. Frontón corto. 2 minifrontones o trinquetes. 2 pistas de pana. Bloque de escalada'),
			('CDM “La Fundi” ', 'C/ Alicante, 14', 'Pabellón. Sala musculación. 2 salas multiusos', '2 pistas polideportivas. 2 pistas de tenis. 2 pistas de pádel'),
			('CDM Playa Victoria ', 'C/ Hierbabuena, 2', 'Piscina (vaso de 25 m y solárium) Sala de musculación. Sala multiusos. 2 sauna', '2. pistas de pádel de cristal'),
			('CDM Casa de Campo', 'Pº. Puerta del Ángel, 7 ', 'Piscina (vaso de 25 m y solárium). Sala de musculación', 'Piscina (vaso de 36, vaso de recreo de 33 e infantil)'),
			('CDM Alcántara', 'C/Alcántara, 26', 'Piscina (vaso de 25 m y vaso de enseñanza). Sala de musculación. 5 salas multiusos', 'Unidades deportivas al aire libre Piscina (vaso de 16,8 x 8,4 metros) y unidades auxiliares al aire libre, terrazas (de entrenamiento, ludoteca y solárium).'),
			('CDM Fuente del Berro ', 'C/ Elvira, 36', 'Piscina (vaso de 25 m). Sala de musculación. 2 salas multiusos', ' - '),
			('CDM El Espinillo ', 'Ctra. de Villaverde a Vallecas, 19', 'Piscina (vaso de 25 m. y vaso de enseñanza). 2 salas multiusos. Sala de psicomotricidad', ' - '),
			('CDM La Almudena ', 'C/ Nicolás Salmerón, 8 B ', 'Piscina (vaso de 25 m. y vaso de enseñanza). Sala de fisioterapia', ' - '),
			('CDM La Vaguada ', 'Avda. Monforte de Lemos, 38 ', 'Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación', ' - '),
			('CDM Pueblo Nuevo ', 'C/ Francisco Rioja, 14 ', 'Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 2 salas multiusos. Sauna ', '3 tenis de mesa'),
			('CDM Los Prunos ', 'C/ Petunias, 30', 'Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 4 salas multiusos. Sauna. Spa', 'Pista de fútbol sala. Pista de baloncesto. 12 pistas de pádel (4 de ellas con cubierta)'),
			('CDM Fabián Roncero ', 'Avda. Séptima, 68 ', 'Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. Sala multiusos', 'Zona de cross-training.'),
			('CDM Moscardó ', 'C/ Andrés Arteaga, 5 ', 'Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. Sala multiusos (cardio)', 'Piscina (vaso de 50 m. y vaso infantil). 2 pistas de pádel. Pista de vóley playa'),
			('CDM LUIS ARAGONÉS ', 'C/ El Provencio, 20 ', 'Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. Sala multiusos. Sala de artes marciales ', 'Piscina (vaso de 50 m. vaso infantil y 2 vasos de recreo). 2 campos de fútbol 11 de césped artificial. 2 campos de fútbol 7 de césped artificial. Pista de vóley playa. 3 pistas de tenis. 4 pistas de pádel. 4 tenis de mesa. Rocódromo.'),
			('CDM Escuelas de San Antón ', 'C/ Farmacia, 13 ', 'Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. Sauna. Spa.', ' - '),
			('CDM San Juan Bautista ', 'C/ Treviana, 1 B ', 'Piscina (vaso de 25 m. y vaso de enseñanza). Sala musculación. Sala multiusos. ', '3 pistas de tenis. 2 pistas de pádel de cristal'),
			('CDM Gallur ', 'C/ Gallur, 2', 'Pista de atletismo. Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. Sala multiuso', 'Campo de fútbol 11 césped artificial (2 campos de fútbol 7). 10 pistas de tenis. Frontón largo. 12 pistas de pádel.'),
			('CDM Barceló ', 'C/ Barceló, 8', 'Pista polideportiva y 3 salas multiusos. ', ' - '),
			('CDM Cuatro Caminos (en construcción). ', 'C/ Bravo Murillo. ', 'Pista polideportiva. Piscina. Salas de musculación. Salas multiusos. Pista deportiva. Solárium.', ' - '),
			('CDM Daoiz y Velarde II ', 'C/ Alberche, 21', 'Sala de musculación y 5 salas multiuso', ' - '),
			('CDM LA CHOPERA', 'Pº. Fernán Núñez, 3 - Parque del Buen Retiro', 'Sala de musculación y sala multiusos', 'Campo de fútbol 11 de césped artificial. 3 . pistas polideportivas. 3 pistas de tenis. 3 pistas de pádel. Circuito de vida'),
			('CDM San Cristóbal', 'Pl. de los Pinazo, 9 ', 'Sala de musculación. Sala multiusos. Sala de artes marciales. Sauna', ' - '),
			('CDM Canódromo ', 'C/ Vía Carpetana, 57 ', 'Sala multiusos', 'Campo de fútbol 11 con 2 campos de fútbol 7 (más campo de fútbol 7 no reglamentario de calentamiento)'),
			('CDM Lago Casa de Campo', 'Pº. Embarcadero, 8 - Casa de Campo', '', 'Lago '),
			('CDM Las Cruces ', 'Avda. de los Poblados, 72 - Parque de las Cruces', 'Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). Sala de musculación. 3 salas multiusos', 'Campo de fútbol 11 de césped artificial. 2 campos de fútbol 7 de césped artificial. 5 pistas de tenis. 8 pistas de pádel (2 de ellas de cristal)'),
			('CDM Francos Rodríguez ', 'C/ Numancia, 11 (sólo verano)', '', 'Piscina (vaso de 50 m. y vaso infantil). Pista de vóley playa. 3 tenis de mesa'),
			('CDM Peñuelas ', 'C/ Arganda, 25 (Sólo verano)', '', 'Piscina (vaso de recreo, vaso gemela y vaso infantil)'),
			('CDM Orcasitas ', 'C/ Rafaela Ibarra, 52 ', 'Unidades cubiertas–Edificio Jesús Rollán: Pabellón. Piscina (vaso de 25 m. y vaso de enseñanza). 2 salas de musculación. 3 salas multiusos. Sala de Fisioterapia e hidroterapia ', 'Piscina (2 vasos de 50 m y un vaso infantil). Pista de atletismo. 3 campos de fútbol 11 de césped artificial. Campo de fútbol 7 de césped artificial. 2 pistas polideportivas. 8 pistas de tenis. 5 pistas de pádel(1 de ellas de cristal). Pista de vóley playa'),
			('CDM Circuito BMX ', 'C/ Embajadores, 316', ' - ', 'Circuito de BMX'),
			('CDM Estanque del Retiro', 'Pº de Colombia, 2 - Parque del Buen Retiro', ' - ', 'Estanque con barcas de recreo'),
			('CDM La Bombilla ', 'C/ Senda del Rey, 8', ' - ', '5 pistas de tenis. 4 pistas de pádel (2 de ellas de cristal). Tenis de mesa'),
			('CDM San Fermín ', 'C/ San Mario, 18 (sólo verano) ', ' - ', 'Piscina (vaso de 50 m. y vaso infantil)'),
			('CDM Santa Ana', 'Pº. Alamedillas, 5 (Sólo verano) ', ' - ', 'Piscina (vaso de recreo y vaso infantil). 2 pistas polideportivas. 4 tenis de mesa'),
			('CDM Tenis Casa de Campo', 'Pº. Camino Príncipe, 2 - Casa de Campo ', ' - ', '15 pistas de tenis. 7 tenis de mesa'),
			('CDM Vallecas ', 'C/ Arroyo del Olivar, 51 (sólo verano)', ' - ', 'Piscina (vaso de recreo y vaso de enseñanza)'),
			('Campo de fútbol del Pozo–Gestión indirecta  ', 'C/ Reguero de Tomateros, 103B ', ' - ', 'Campo de fútbol '),
			('Circuito BMX / Radiocontrol.', 'Avda. Vía Lusitana, 19 (Parque Sur)', ' - ', 'Circuito deportivo y pista de automodelismo. '),
			('IDB 2.100 PAU ', 'Avda. de Cerro Milano c/v C/ Peñaranda de Bracamonte. ', ' - ', 'Pista polideportiva y pista de baloncesto '),
			('IDB 2.75 PAU ', 'Avda. de la Gavia c/v C/Congosto. ', ' - ', 'Pista de skate '),
			('IDB 3.16 PAU ', 'C/ Alto del Retiro, 13. ', ' - ', 'Pista polideportiva y pista de baloncesto '),
			('IDB Ademo (Arroyo Fontarrón) ', 'C/ Arroyo Fontarrón, 389 ', ' - ', 'Pista de fútbol sala '),
			('IDB Alameda de Osuna I ', 'C/ Balandro, 1 A ', ' - ', '2 pistas de baloncesto '),
			('IDB Alameda de Osuna II ', 'C/ Paseo Alameda de Osuna, 48 ', ' - ', 'Pista de baloncesto y pista de fútbol sala '),
			('IDB Alas ', 'C/ Alas, 8 ', ' - ', 'Pista de fútbol sala y pista baloncesto '),
			('IDB Albaicín ', 'C/ Albaicín, 19 ', ' - ', 'Pista polideportiva '),
			('IDB Albaida ', 'C/ Albaida, 3 (Parque San Blas) ', ' - ', 'Pista de patinaje '),
			('IDB Alcalde Martín de Alzaga ', 'C/ Alcalde Martín de Alzaga, 2,', ' - ', '2 pistas de baloncesto 3x3'),
			('IDB Alerce ', 'C/ Alerce, 31 - Junto M-40 ', ' - ', 'Pista polideportiva '),
			('IDB Alfonso XIII ', 'C/ Alfonso XIII, 136 ', ' - ', '2 pistas de baloncesto. Pista de patinaje. 2 campos de bolos y petanca '),
			('IDB Alhaurín ', 'C/ Alhaurín, 6 ', ' - ', 'Campo de fútbol 7. Pista de baloncesto. Pista de patinaje. Pista de petanca '),
			('IDB Alicún ', 'C/ Alicún, 24 ', ' - ', 'Pista de baloncesto '),
			('IDB Aliseda ', 'C/ Aliseda, 19 c/v Real Betis ', ' - ', 'Pista polideportiva '),
			('IDB Almudena ', 'C/ Nicolás Salmerón, 8 B ', ' - ', 'Campo de fútbol 11 de césped artificial y pista polideportiva '),
			('IDB Ambulatorio (El Paraíso) ', 'C/ Ajofrín, 8 B (Parque Ajofrín) ', ' - ', 'Pista de fútbol sala y 2 pistas de baloncesto '),
			('IDB Americio ', 'C/ Americio, 2 (zona verde del APE 17.01) ', ' - ', 'Pista de minibaloncesto y 2 pistas de petanca '),
			('IDB Ana Tutor ', 'Avda. Cardenal Herrera Oria, junto nº 216 ', ' - ', 'Pista de fútbol sala y pista de patinaje'),
			('IDB Andévalo ', 'C/ Andévalo, 6 ', ' - ', 'Pista de fútbol sala '),
			('IDB Anfevi', 'C/ Hacienda de Pavones, 127 ', ' - ', 'Pista de patinaje y en su interior una pista de hockey patines '),
			('IDB Anfevi', 'C/ Hacienda de Pavones, 127 posterior ', ' - ', 'Pista polideportiva '),
			('IDB Aniceto Marinas ', 'C/ Aniceto Marinas, 106 ', ' - ', 'Pista de baloncesto '),
			('IDB Antonio Machado ', 'C/ Antonio Machado, 14 (PO)', ' - ', '2 pistas de baloncesto 3x3 '),
			('IDB Arcaute ', 'Avda. Invierno, 1 ', ' - ', 'Pista polideportiva '),
			('IDB Arcos de Jalón c/v Albericia ', 'C/ Arcos de Jalón, 114 c/v C/ Albericia ', ' - ', 'Pista de fútbol sala. 2 pistas de baloncesto. Pista de voleibol. Pista de patinaje '),
			('IDB Arequipa ', 'C/ Arequipa, 12', ' - ', '2 pistas de bolos y petanca '),
			('IDB Arganda ', 'C/ Arganda, 10 ', ' - ', 'Pista de fútbol sala '),
			('IDB Arjona ', 'C/ Concejal Francisco José Jiménez Martín, 11 ', ' - ', 'Campo de fútbol 11 de tierra '),
			('IDB Arroyo Belincoso', 'Frente Avenida Doctor García Tapia, 76 ', ' - ', 'Pista polideportiva '),
			('IDB Arroyo Media Legua–Gestión: Autorización demanial', 'Avda. Trece Rosas, 3-B ', ' - ', 'Campo de fútbol 11 de césped artificial. 2 pistas de fútbol sala. 2 pistas de baloncesto. Pista de calva '),
			('IDB Arroyo Opañel ', 'C/ Arroyo de Opañel, 1 ', ' - ', 'Pista polideportiva '),
			('IDB Aster – Lirios ', 'C/ Alfonso XIII, 124 ', ' - ', 'Pista de fútbol sala '),
			('IDB Auditorio de Chamartín', 'Plaza Joaquín Rodrígo,1 ', ' - ', 'Pista de baloncesto '),
			('IDB Auditorio de Moratalaz ', 'C/ Hacienda de Pavones, 209 ', ' - ', 'Pista de fútbol sala y 2 tenis de mesa '),
			('IDB Avenida de Brasil ', 'Avda. de Brasil, 19 B (sobre parking) ', ' - ', 'Pista de fútbol sala '),
			('IDB Avenida de Los Rosales ', 'Avda. de los Rosales, 123 ', ' - ', 'Pista polideportiva '),
			('IDB Avenida de Moratalaz - M-30 ', 'C/ Ramón Areces, 1 (frente Avenida de Moratalaz, 13) ', ' - ', 'Pista de baloncesto y pista de patinaje '),
			('IDB Avenida de Niza ', 'Avda. de Niza, 29 ', ' - ', 'Pista de patinaje '),
			('IDB Ayacucho ', 'C/ del Nevado del Ruíz, 2 (Cubierta de P.A.R.) ', ' - ', 'Pista de baloncesto '),
			('IDB Bacares ', 'C/ Bacares, 9', ' - ', 'Rocódromo. Workout '),
			('IDB Bacares (Fútbol) ', 'C/ Bacares, 27 ', ' - ', 'Campo de fútbol sala pavimentado. Pista de minibaloncesto. Pista de patinaje. Pista de voleibol. Pista de skate'),
			('IDB Bahía de Santander II ', 'C/ Bahía de Santander, 64 ', ' - ', 'Pista de fútbol sala '),
			('IDB Barrio Aeropuerto ', 'C/ Medina de Pomar, frente nº 14 ', ' - ', 'Campo de fútbol 11 (tierra). Pista polideportiva. 2 tenis de mesa '),
			('IDB Barrio de las Cárcavas ', 'C/ Montoro, 4 ', ' - ', 'Pista de skate '),
			('IDB Barrio de Santa Ana – Andrés Navarrete ', 'C/ Hospitalet de Llobregat, 11 ', ' - ', 'Campo de fútbol 11 de césped artificial. Campo de fútbol 7 de césped artificial. 2 pistas de bolos y petanca '),
			('IDB Barrio El Querol – Spartak de Manoteras ', 'C/ Tijola, 1 ', ' - ', 'Campo de fútbol 11 de tierra '),
			('IDB Barrio Goya ', 'Avda. de los Caprichos c/v C/ Caramuel ', ' - ', 'Campo de fútbol 11 de tierra '),
			('IDB Barrio IV ', 'C/ Luis de Hoyos Sainz, 152 ', ' - ', 'Pista polideportiva '),
			('IDB Baterías-Barrio de la Alegría ', 'C/ Baterías, 2 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. Pista de patinaje '),
			('IDB Belzunegui', 'Plaza de Alooz, 4 ', ' - ', 'Pista de baloncesto '),
			('IDB Bicitrial –Gestión indirecta: Federación de Ciclismo', 'C/ Talbot, 10 (PO) ', ' - ', 'Circuito de bicitrial. 2 tenis de mesa no se encuentran operativos. Circuito de vida. '),
			('IDB Boston ', 'C/ Boston, 1 ', ' - ', 'Pista polideportiva cubierta y tenis de mesa '),
			('IDB Brujas', 'Hacienda de Pavones, 356 esquina Arroyo Fontarrón ', ' - ', 'Pista de fútbol sala '),
			('IDB Brunete (El Pardo) ', 'C/ Brunete, 1 ', ' - ', 'Pista de baloncesto y pista de fútbol sala '),
			('IDB Burgo de Osma ', 'C/ Burgo de Osma, 5 ', ' - ', 'Pista polideportiva '),
			('IDB Burgos ', 'Avda. de Burgos, 18 B', ' - ', '7 pistas de pádel '),
			('IDB Calanda ', 'C/ Calanda, 30 (cubierta P.A.R.) ', ' - ', 'Pista de chito '),
			('IDB Caleruega ', 'C/ Caleruega, 52 ', ' - ', 'Pista de baloncesto '),
			('IDB Caleruega-Arte ', 'C/ Caleruega, 65 c/v C/ Arte, 2 ', ' - ', 'Pista de baloncesto '),
			('IDB Camino de la Suerte ', 'C/ Camino de la Suerte, 25 ', ' - ', 'Campo de fútbol 11 de césped artificial y campo de fútbol 7 de tierra '),
			('IDB Camino Viejo de Leganés', 'Cº Viejo de Leganés, 179 B (sobre P.A.R.) ', ' - ', 'Pista polideportiva '),
			('IDB Campo Aragón ', 'C/ Antonio Mairena, 23 ', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB Campo Azul ', 'C/ Río Esmeralda esquina calle Tánger ', ' - ', 'Pista polideportiva '),
			('IDB Campo de fútbol San Cristóbal de Los Ángeles ', 'C/ Rocafort, 9 ', ' - ', 'Campo de fútbol de césped artificial '),
			('IDB Canal de Panamá ', 'C/ Canal de Panamá, 4 ', ' - ', 'Pista de fútbol sala '),
			('IDB Canillas – Club Deportivo Canillas ', 'C/ Agustín de Iturbide, 1 ', ' - ', 'Campo de fútbol 11 y campo de fútbol sala de césped artificial '),
			('IDB Cañada del Santísimo ', 'C/ Cañada del Santísimo c/v C/ Embalse de Navacerrada. ', ' - ', 'Pista polideportiva y pista de baloncesto '),
			('IDB Cárcavas Oeste I ', 'C/ Carmen Rico Godoy, 40 ', ' - ', 'Pista de baloncesto '),
			('IDB Cárcavas Oeste II ', 'C/ San Andrés de Rabaneda, 1 ', ' - ', 'Pista polideportiva '),
			('IDB Cárcavas', 'Camino de Valdehigueras, 46 ', ' - ', 'Pista de fútbol sala '),
			('IDB Carlos II ', 'Avda. de Niza, 9 ', ' - ', 'Pista polideportiva '),
			('IDB Carlos Solé ', 'C/ Carlos Solé, 19', ' - ', '2 pistas de tenis. 1 Frontón corto. 2 pistas de pádel '),
			('IDB Caronte ', 'C/ Caronte, 4 ', ' - ', 'Pista polideportiva '),
			('IDB Carril del Conde ', 'C/ Carril del Conde c/v C/ del Puerto Real, 7 ', ' - ', 'Pista de fútbol sala '),
			('IDB Casa de Campo Lago I', 'Pº. de María Teresa, 7 (PO) ', ' - ', 'Campo de fútbol 11 '),
			('IDB Casa de Campo Lago IV', 'Pº. Piñoneros, 4 ', ' - ', 'Campo de fútbol 11 y campo de fútbol 7 '),
			('IDB Casalarreina ', 'C/ Casalarreina, 30 ', ' - ', 'Pista de baloncesto 3x3. Pista polideportiva '),
			('IDB Casino de la Reina ', 'C/ Embajadores, 66 c/v C/ Casino 3 ', ' - ', 'Pista polideportiva y pista de baloncesto '),
			('IDB Castroserna ', 'C/ Castroserna, 2 ', ' - ', 'Campo de fútbol 11 de tierra y tenis de mesa '),
			('IDB Cazorla ', 'C/ Libros, 3', ' - ', 'Pista de fútbol sala '),
			('IDB CD Moscardó – Estadio Román Valero ', 'C/ Andrés de Arteaga, 3', ' - ', '1 campo de fútbol 11 de césped artificial '),
			('IDB Cementerio Civil ', 'Avda. de Daroca, 101 ', ' - ', 'Pista de fútbol sala (próximo cambio a pista ecuavoley) '),
			('IDB Centro de Mayores Ciudad de Méjico ', 'C/ Rafael Finat, 47 ', ' - ', 'Pista de bolos y petanca '),
			('IDB Cerro Blanco–Gestión indirecta  ', 'C/ Albardín, 7 c/v C/ Cerro Blanco ', ' - ', 'Pista de baloncesto. Pista de balonmano. 2 pistas de bolos y petanca '),
			('IDB Cerro Cabezuelos ', 'C/ Villalobos, 46 ', ' - ', 'Campo de fútbol 11 de tierra '),
			('IDB Cerro Negro ', 'C/ Cerro Negro, 5 ', ' - ', 'Pista de baloncesto. Pista de patinaje. Tenis de mesa. 2 pistas de bolos y petanca '),
			('IDB Circuito de Automodelismo ', 'C/ Navamures,10', ' - ', 'Circuito de automodelismo '),
			('IDB Circuito de bicicletas Enrique Otero', 'Parque Casa de Campo', ' - ', 'Circuito de bicicletas '),
			('IDB Circuito de footing Casa de Campo', 'Casa de Campo', ' - ', 'Recorrido interior Casa de Campo, circuito de footing '),
			('IDB Circuito de footing Dehesa de La Villa', 'Parque Dehesa de la Villa', ' - ', 'Circuito de footing '),
			('IDB Circuito Natural de Footing Retiro', 'Parque de El Buen Retiro', ' - ', 'Circuito de footing '),
			('IDB Ciudad de los Ángeles ', 'C/ Anoeta, 14 B (parque Ciudad de los Ángeles)', ' - ', '2 pistas de baloncesto y pista de patinaje '),
			('IDB Ciudad Pegaso I ', 'C/ Uno, 2 B ', ' - ', 'Pista de fútbol sala '),
			('IDB Ciudad Pegaso II ', 'Avda. Sexta, 4', ' - ', '3 pistas de bolos y petancas '),
			('IDB Ciudad Pegaso III ', 'C/ Once, 7 ', ' - ', 'Pista polideportiva '),
			('IDB Clara del Rey ', 'C/ Clara del Rey, 61 ', ' - ', 'Pista polideportiva '),
			('IDB Club de Petanca Esperanza de Canillas ', 'C/ Silvano, 63', ' - ', '6 pistas de bolos y petanca '),
			('IDB Club de Petanca Peonias ', 'C/ de las Peonías, 2', ' - ', '3 pistas de bolos y petanca '),
			('IDB Cocheras ', 'C/ Cocheras, 1-3 ', ' - ', 'Pista de fútbol. Pista de baloncesto. Pista de patinaje. Zona de parkour (bajo el puente de Doctor Esquerdo) '),
			('IDB Colombia ', 'C/ Colombia, 59 ', ' - ', 'Pista de patinaje '),
			('IDB Colonia Euskalduna ', 'C/ Hermandad de Donantes de Sangre, 7', ' - ', '2 pistas de fútbol sala/balonmano '),
			('IDB Colonia los Taxistas ', 'C/ Sierra Cuerda Larga detrás de los nº 41, 43, 45 y 47', ' - ', '2 pistas de fútbol sala y 2 pistas de baloncesto '),
			('IDB Colonia Marconi ', 'C/ Principal, 1 ', ' - ', 'Pista polideportiva. Pista de patinaje. 2 pistas de tenis. 4 minifrontones o trinquetes '),
			('IDB Colonia San Cristóbal de los Ángeles ', 'C/ Rocafort, 2 posterior', ' - ', '2 pistas polideportivas '),
			('IDB Colonia Sierra del Valle ', 'C/ Payaso Fofó, 9 ', ' - ', 'Pista de fútbol sala y pista de baloncesto '),
			('IDB Colonia Vilda ', 'C/ Puentelarra c/v Avda. Santa Eugenia', ' - ', '2 pistas polideportivas '),
			('IDB Concejal Gabriel Fernández. (Parque Cuña Verde) ', 'C/ Cuart de Poblet, 6 ', ' - ', 'Campo de fútbol 11. 2 campos de fútbol 7 de césped artificial. 2 pistas polideportivas (baloncesto y ecuavoley). Tenis de mesa '),
			('IDB Conde Duque ', 'C/ Santa Cruz de Marcenado, 21 ', ' - ', 'Pista de fútbol sala. Pista de bolos y petanca. Pista de chito '),
			('IDB Condesa de Venadito ', 'C/ Condesa de Venadito, 7 ', ' - ', 'Pista de baloncesto de una canasta. Pista de fútbol sala. Pista de BMX. Pista de skate '),
			('IDB Cordel de Pavones I ', 'C/ Cordel de Pavones, 9 ', ' - ', 'Pista de tenis. 4 pistas de pádel. 3 tenis de mesa '),
			('IDB Cordel de Pavones II ', 'C/ Cordel de Pavones, 11', ' - ', '2 pistas de fútbol sala. 2 pistas de baloncesto. Frontón corto. 3 minifrontones '),
			('IDB Cuevas de Almanzora ', 'C/ Mojácar, 2 ', ' - ', 'Pista de fútbol sala '),
			('IDB Cuña Verde ', 'C/ Villamil, 126 c/v Camino del Chorrillo', ' - ', '2 pistas polideportivas. 2 pistas de baloncesto. 3 tenis de mesa '),
			('IDB David González Rubio – Pradolongo ', 'C/ Dr. Tolosa Latour, 14 (Parque Pradolongo)', ' - ', '2 campos de fútbol 11 de césped artificial. Pista de fútbol sala. Pista polideportiva '),
			('IDB de Las Vistillas ', 'Pza. Gabriel Miró s/n ', ' - ', 'Pista de fútbol-sala '),
			('IDB Dehesa de Moratalaz ', 'Avda. Doctor García Tapia, 117 ', ' - ', 'Campo de fútbol 11 de césped artificial'),
			('IDB Dehesa del Príncipe ', 'Avda. de los Arqueros, 15 y 39 ', ' - ', 'Pista polideportiva. 2 pistas de bolos y petanca '),
			('IDB Diana ', 'C/ Galeón, 25 B ', ' - ', 'Pista de fútbol sala y 2 pistas de baloncesto '),
			('IDB Diego de Valderrábano ', 'C/ Corregidor Diego de Valderrábano, 26 ', ' - ', 'Pista polideportiva y pista de bolos y petanca '),
			('IDB Doctor Cirajas ', 'C/ Doctor Cirajas, 3', ' - ', '2 pistas de baloncesto '),
			('IDB Doctor García Tapia- Carmen Amaya ', 'Avda. Doctor García Tapia 28-30 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. 2 campos de chito '),
			('IDB Doctor Vallejo Nájera ', 'C/ Gasómetro, 32 ', ' - ', 'Pista de baloncesto '),
			('IDB Dracena ', 'C/ Drácena,42 ', ' - ', 'Pista de hockey sobre patines '),
			('IDB Echegaray ', 'C/ Encomienda de Palacios, 324 ', ' - ', 'Pista polideportiva '),
			('IDB Eduardo Barreiros ', 'C/ Eduardo Barreiros, 63 ', ' - ', 'Pista de baloncesto '),
			('IDB El Bosco ', 'C/ El Bosco, 14 esquina C/ Ramón Pérez de Ayala ', ' - ', 'Pista de fútbol sala de tierra '),
			('IDB El Bosque', 'Pza. de Golmayo, 17 ', ' - ', 'Pista de fútbol sala '),
			('IDB El Capricho', 'Pº. Alameda de Osuna, 46 ', ' - ', 'Campo de fútbol 11 de césped artificial. Campo de fútbol 7(tierra) '),
			('IDB El Cruce ', 'C/ Santiago Amón, 6 y 8', ' - ', '2 pistas polideportivas '),
			('IDB El Espinillo I (Auditorio) ', 'C/ Unanimidad, 3 c/v cl. Tertulia.', ' - ', '2 pistas polideportivas con gradas y pista de patinaje '),
			('IDB El Espinillo II ', 'C/ Consenso, 3 y 5 ', ' - ', 'Campo de fútbol 7 de césped artificial. Pista polideportiva. 3 pistas de tenis. 2 tenis de mesa '),
			('IDB El Espinillo III ', 'C/ Unanimidad, 23 y 25 (parque del Espinillo) ', ' - ', 'Pista polideportiva '),
			('IDB El Parque ', 'C/ Comandante Fortea, 25 ', ' - ', 'Pista polideportiva '),
			('IDB El Pedernoso - Parque de Villa Rosa - Paco Caño ', 'C/ Las Pedroñeras, 42', ' - ', '2 pistas de baloncesto. 2 tenis de mesa '),
			('IDB El Plantío – Rafael Villa ', 'C/ Rafael Villa, 74 ', ' - ', 'Pista de baloncesto '),
			('IDB El Torero ', 'C/ Torero, 10 c/v C/ Antonio López ', ' - ', 'Pista de baloncesto y pista de patinaje '),
			('IDB El Vandel ', 'C/ Florencio Cano Cristóbal, esquina c/ El Paular ', ' - ', 'Campo fútbol 7 tierra. Pista de fútbol sala. Pista de baloncesto. '),
			('IDB Electra ', 'C/ Cronos, 65 ', ' - ', 'Pista polideportiva. Pista de baloncesto. Tenis de mesa. 2 pistas de chito '),
			('IDB Embajadores M 30 ', 'C/ Puerto de la Cruz Verde, 29 ', ' - ', 'Pista de fútbol sala '),
			('IDB Eros ', 'C/ Eros, 6 ', ' - ', 'Pista de fútbol sala '),
			('IDB Escultor Peresejo ', 'C/ Escultor Peresejo, 11 ', ' - ', 'Campo de fútbol 11 '),
			('IDB Esfinge ', 'C/ Esfinge, 58 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. 14 pistas de bolos y petanca. 8 pistas de calva '),
			('IDB Espacio Polivalente Embajadores, 18 ', 'C/ Embajadores, 18 ', ' - ', 'Pista de fútbol sala y pista de petanca '),
			('IDB Esperanza I – Club Virgen de la Esperanza ', 'C/ Silvano, 65 ', ' - ', 'Campo de fútbol 11 de césped artificial (con 2 marcajes de fútbol 7). Pista de fútbol sala de césped artificial '),
			('IDB Esperanza II –Pista polideportiva ', 'C/ Silvano, 61 ', ' - ', 'Pista polideportiva '),
			('IDB Estanque de las Tormentas ', 'C/ Arroyo Pozuelo, 6 ', ' - ', 'Campo de fútbol 7 y 2 pistas polideportivas '),
			('IDB Estefanita ', 'C/ Estefanita detrás del nº 7 –CEIP El Greco- Ctra. San Martín de la Vega ', ' - ', 'Pista de baloncesto '),
			('IDB Estibaliz ', 'C/ Estibaliz, 30', ' - ', 'Frontón corto '),
			('IDB Euterpe ', 'C/ Euterpe, ', ' - ', 'Campo de fútbol 11 de césped artificial -con marcaje de 2 campos de fútbol 7 transversales-. '),
			('IDB Eva Duarte ', 'C/ Doctor Gómez Ulla, 9', ' - ', '3 pistas polideportivas. 2 pistas de pádel. 2 tenis de mesa. 2 pistas de bolos y petanca. Pista de chito '),
			('IDB Evangelios – Almendrales ', 'C/ Evangelios, 4 ', ' - ', 'Pista polideportiva '),
			('IDB Fermín Caballero ', 'C/ Fermín Caballero, 88 ', ' - ', 'Pista de patinaje. 6 pistas de bolos y petanca. 2 pistas de chito '),
			('IDB Fonsagrada ', 'Pza. Fonsagrada, 6 B ', ' - ', 'Pista polideportiva '),
			('IDB Francisco Laguna ', 'C/ Francisco Laguna, 26', ' - ', '2 pistas de fútbol sala y pista de baloncesto '),
			('IDB Frontón de la Tudelillas ', 'C/ Tudelillas c/v Avda. Pablo Iglesias, 62', ' - ', 'Frontón corto '),
			('IDB Frontón Orcasitas ', 'Avda. Rafaela Ibarra, 103 (Parque Orcasitas)', ' - ', 'Frontón Corto '),
			('IDB Frontón Polideportivo San Fermín ', 'C/ San Máximo, 10', ' - ', 'Frontón corto '),
			('IDB Frontón San Fermín ', 'C/ Camino de Perales, 136', ' - ', 'Frontón corto (con gradas para 400 personas) '),
			('IDB Fuente de Lima ', 'C/ Fuente de Lima, 28 ', ' - ', 'Pista de baloncesto '),
			('IDB Fuerte de Navidad ', 'C/ Fuerte de Navidad c/v C/ La Isabela ', ' - ', 'Pista de baloncesto '),
			('IDB Gabriela Mistral ', 'C/ Rosalía de Castro, 69 (Parque Gabriela Mistral) ', ' - ', 'Pista de baloncesto '),
			('IDB Galeón ', 'C/ Galeón, 1 ', ' - ', '2 pistas de baloncesto '),
			('IDB Garrovillas', 'Pza. Garrovillas. (cubierta P.A.R.) ', ' - ', 'Pista de patinaje. 3 pistas de bolos y petanca. Pista de chito '),
			('IDB General Millán Astray ', 'C/ General Millán Astray, 4 ', ' - ', 'Pista polideportiva '),
			('IDB General Saliquet ', 'C/ General Saliquet, 22 y 28 ', ' - ', 'Campo de fútbol 11 de tierra. Pista polideportiva. Tenis de mesa '),
			('IDB Glorieta Avenida de San Luis ', 'C/ Añastro, 78 ', ' - ', 'Pista polideportiva '),
			('IDB Glorieta de Segovia', 'Pº. Ciudad de Plasencia ', ' - ', 'Pista de tenis de mesa '),
			('IDB Gorrión ', 'C/ Gorrión, 36 (Parque de San Isidro) ', ' - ', 'Campo de fútbol 11 y pista polideportiva '),
			('IDB Gran Vía de Hortaleza ', 'Cubierta del túnel de la Calle Costa Rica a Gran Vía de Hortaleza ', ' - ', 'Pista de patinaje y pista de calva '),
			('IDB Guadalajara ', 'Avda. Guadalajara, 18 ', ' - ', 'Campo de fútbol 11 de césped artificial. 2 campos de fútbol 7 de césped artificial. Campo de minipitch '),
			('IDB Hermanos Trueba ', 'C/ Hermanos Trueba, 30 ', ' - ', 'Pista de fútbol sala. 2 pistas de baloncesto. Pista de voleibol '),
			('IDB Hogar del Ferroviario Col. Ferroviarios - ', 'C/ Manuel María Arrillaga esquina Corregidor Diego de Valderrábano ', ' - ', 'Campo de fútbol 7 de tierra '),
			('IDB Hornero ', 'C/ Hornero, 1 ', ' - ', 'Pista polideportiva '),
			('IDB Huerta de la Salud ', 'C/ Alcobendas, 3 ', ' - ', 'Pista de baloncesto '),
			('IDB Illescas ', 'C/ Illescas c/v Pº. de Extremadura. (cubierta P.A.R.) ', ' - ', 'Pista polideportiva y 2 pistas de bolos y petanca '),
			('IDB Imagen ', 'C/ Imagen, 23', ' - ', '2 pistas de baloncesto '),
			('IDB Isabel Patacón ', 'C/ Isabel Patacón, 7 ', ' - ', 'Pista polideportiva '),
			('IDB Isla de Tabarca (Peñagrande) ', 'C/ Santiago de Compostela, 104 c/v C/ Isla de Tabarca ', ' - ', 'Campo de fútbol 11 de césped artificial. Pista de fútbol sala de césped artificial. Pista de baloncesto. 3 pistas de baloncesto 3x3 '),
			('IDB Islas Jarvi ', 'C/ Islas Jarvi,5 ', ' - ', 'Pista de bolos y petanca '),
			('IDB Iván de Vargas ', 'Travesía Iván de Vargas, 4 ', ' - ', 'Pista polideportiva '),
			('IDB Jacinto Verdaguer ', 'C/ de la Verdad, 2 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. Pista de patinaje. 2 tenis de mesa '),
			('IDB Jardín Canarias ', 'C/ Canarias, 19 ', ' - ', 'Pista de bolos y petanca '),
			('IDB Jardín de Portugalete ', 'C/ Ulises, 23 ', ' - ', 'Pista de baloncesto '),
			('IDB Jardín Papelera Peninsular ', 'C/ Arganda, 3', ' - ', '2 pistas de tenis y 2 pistas de patinaje '),
			('IDB Jardines Alhambra ', 'C/ Alhambra c/v C/ Carlos Fuentes ', ' - ', 'Pista polideportiva y pista de patinaje '),
			('IDB Jardines de Bucaramanga ', 'Avda. de Bucaramanga, 2', ' - ', '2 pistas de baloncesto 3x3. Tenis de mesa. 2 pistas de bolos y petanca. Pista de chito '),
			('IDB Jardines de José Luis Sampedro (junto al Centro Cultural Galileo)', 'Jardines de José Luis Sampedro', ' - ', 'Circuito de bicicletas'),
			('IDB Jardines General Fanjul ', 'Avda. General Fanjul, 110 y 144.', ' - ', '2 pistas de fútbol sala. Pista de baloncesto 3x3 . Tenis de mesa '),
			('IDB Jardines Vía Carpetana ', 'C/ Vía Carpetana c/v C/ Laguna ', ' - ', 'Pista de patinaje '),
			('IDB Jazmín ', 'C/ Jazmín, 36 ', ' - ', 'Pista polideportiva '),
			('IDB Jesús Aprendiz ', 'C/ Antonio Díaz Cañabate, 9 ', ' - ', 'Pista de fútbol sala y pista de baloncesto '),
			('IDB Jesús Divino Obrero ', 'C/ Humanes con vuelta a calle Tossa ', ' - ', 'Pista de fútbol sala (techada). 2 pistas de baloncesto '),
			('IDB Joaquín Ibarra ', 'C/ Joaquín Ibarra, frente nº 24 ', ' - ', 'Pista polideportiva '),
			('IDB José de Cadalso ', 'C/ José de Cadalso c/v C/ General Romero Basart. ', ' - ', 'Pista de patinaje '),
			('IDB José de Pasamonte ', 'Avda. Doctor García Tapia, 51 ', ' - ', 'Pista de baloncesto '),
			('IDB José Durán ', 'Avda. Parque Palomeras Bajas, 10 ', ' - ', 'Campo de fútbol césped artificial. Pista de fútbol sala. 2 pistas de baloncesto '),
			('IDB Juan Clemente Núñez ', 'C/ Juan Clemente Núñez, 1 ', ' - ', 'Pista de fútbol sala '),
			('IDB Juan de Mariana ', 'C/ Juan de Mariana, 8-10 ', ' - ', 'Pista de fútbol sala y 2 tenis de mesa '),
			('IDB Juan de Vera ', 'C/ Juan de Vera, 15 – Plaza del Casar de Cáceres ', ' - ', 'Pista de baloncesto '),
			('IDB Julián González ', 'C/ Julián González, 4 ', ' - ', 'Pista baloncesto '),
			('IDB la Albufera ', 'Explanada metro Miguel Hernández ', ' - ', 'Pista de Patinaje y 5 pistas de tenis de mesa '),
			('IDB La Cabrera ', 'C/ La Cabrera, 33 ', ' - ', 'Campo de fútbol 11 de césped artificial. 2 pistas de fútbol sala de césped artificial. 2 tenis de mesa. Minipitch '),
			('IDB La Chimenea ', 'C/ Vallandes, 5 ', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB La Mancha ', 'C/ Tomelloso, 21 B', ' - ', '2 tenis de mesa '),
			('IDB La Masó ', 'C/ La Masó, 34', ' - ', '15 pistas de pádel. '),
			('IDB La Perla ', 'C/ Corindón, 3 ', ' - ', 'Campo de fútbol 11 de césped artificial. Pista de fútbol sala. 4 pistas de pádel '),
			('IDB La Unión ', 'C/ Enrique García Álvarez, 58. ', ' - ', 'Campo de fútbol 11 de césped artificial y 4 pistas de pádel cubiertas '),
			('IDB Laminador de Tormentas- Valdebebas ', 'C/ Antonio Flórez s/n esq. Avda. Francisco Javier Sáenz de Oiza', ' - ', '4 pistas polideportivas '),
			('IDB Lonja de la Seda ', 'C/ Lonja de la Seda, 32 (P.A.U.) ', ' - ', 'Pista polideportiva. Pista de baloncesto. Pista de patinaje. Pista bolos y petanca. '),
			('IDB Los Arbolitos ', 'C/ Ronda del Sur, 6 B ', ' - ', 'Campo de rugby '),
			('IDB Los Caprichos ', 'Avda. de los Caprichos, 1 ', ' - ', 'Sala multiusos cubierta. Pista polideportiva (fútbol sala y 2 baloncestos transversales). 2 pistas de tenis. 4 pistas de pádel de cristal '),
			('IDB Los Cármenes ', 'C/ Alhambra, 35', ' - ', '2 campos de fútbol 11 de tierra. Pista de fútbol sala. Pista polideportiva. 4 pistas de voleibol. Pista de baloncesto. Tenis de mesa '),
			('IDB Los Coronales ', 'C/ Bahía de Málaga, 5 ', ' - ', 'Campo de fútbol 11 de césped artificial. 2 campos de fútbol 7, de césped artificial '),
			('IDB Los Llanos ', 'C/ Florencio Castillo, 3', ' - ', '2 pistas de tenis '),
			('IDB Los Morales ', 'C/ Los Morales, 31 (P.A.U.) ', ' - ', 'Pista de baloncesto '),
			('IDB Los Poblados ', 'Avda. de los Poblados, 106 ', ' - ', 'Campo de fútbol 11. Pista de fútbol sala. Pista de baloncesto. Pista de patinaje '),
			('IDB Los Rosales I ', 'Avda. de los Rosales, 133 ', ' - ', 'Pista polideportiva, con cubierta y pista de patinaje con cubierta y gradas '),
			('IDB Los Rosales II ', 'Avda. de los Rosales, 135 ', ' - ', 'Campo de fútbol de césped artificial '),
			('IDB Lucano (Arquitecto Antonio Palacios) ', 'C/ Esfinge, 74 B ', ' - ', 'Campo de fútbol 11. Pista de fútbol sala. Pista de bolos y petanca '),
			('IDB Luis Buitrago ', 'C/ Luis Buitrago, 7 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. Pista de patinaje. Próximo Rocódromo '),
			('IDB Luis Mitjans ', 'C/ Luis Mitjans, 15 ', ' - ', 'Pista de baloncesto '),
			('IDB Lyon - Flandes ', 'C/ Lyon, 9 B ', ' - ', 'Pista de fútbol sala '),
			('IDB Machupichu ', 'Avda. Machupichu, 50 ', ' - ', 'Pista de fútbol sala (techada). Pista polideportiva '),
			('IDB Madrid - Las Tablas ', 'C/ Frómista frente nº5 ', ' - ', 'Pista de baloncesto. Campo de fútbol 7. Pista de hockey. '),
			('IDB Maíz ', 'C/ Ricardo Beltrán y Rózpide, 28 (Frente C/ Maíz)', ' - ', 'Tenis de mesa '),
			('IDB Mallorca-Agastia ', 'C/ Agastia, c/v Juan Pérez Zúñiga', ' - ', '2 pistas de baloncesto '),
			('IDB Manizales ', 'C/ Galapa, 10 (cubierta P.A.R.) ', ' - ', 'Pista de fútbol sala '),
			('IDB Mar de Japón ', 'C/ del Mar de Japón, 7 ', ' - ', 'Pista de patinaje '),
			('IDB Maracena ', 'C/ Maracena, 1 ', ' - ', 'Pista de baloncesto '),
			('IDB María de Austria ', 'C/ Vía Lusitana (Parque Emperatriz Mª de Austria)', ' - ', 'Circuito de BMX. Pista de Voleibol. Pista de bolos y petanca. Pista de chito. Pista de calva. Pista de automodelismo '),
			('IDB María de Villota. ', 'C/ Estefanita. 3', ' - ', 'Campo de fútbol 7. Campo de fútbol 5. Pista polideportiva. 2 pistas de baloncesto 3x3. 2 pistas de pana '),
			('IDB María Inmaculada', 'Camino de las Cruces, 5 ', ' - ', 'Pista polideportiva '),
			('IDB Maris Stella–Gestión indirecta ', 'C/ Dr. Tolosa Latour, 18 ', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB Martala I ', 'C/ Pico de los Artilleros, 5 posterior ', ' - ', 'Pista polideportiva . 3 tenis de mesa. 3 pistas de chito '),
			('IDB Mártires Maristas ', 'C/ Maristas c/v C/ Antonio Machado ', ' - ', 'Pista de baloncesto '),
			('IDB Maruja Mallo ', 'C/ Maruja Mallo, 7 ', ' - ', 'Pista polideportiva '),
			('IDB Matilde Gayo ', 'C/ Matilde Gayo, 4 (cubierta P.A.R.) ', ' - ', 'Pista de baloncesto y tenis de mesa '),
			('IDB Medio Amposta ', 'C/ Alberique, 12 c/v C/ Alconera', ' - ', '2 pistas polideportivas '),
			('IDB Mercedes Arteaga ', 'C/ Mercedes Arteaga con San Pantaleón ', ' - ', 'Pista polideportiva '),
			('IDB Miguel Aracil ', 'C/ Joaquín Lorenzo,39 ', ' - ', 'Pista de fútbol sala de tierra '),
			('IDB Miguel Hernández (Parque lineal Palomeras) ', 'C/ Miguel Hernández v/c C/Andaluces ', ' - ', 'Pista de fútbol sala y pista de baloncesto '),
			('IDB Miguel Riesco - Ramón Power ', 'C/ Miguel Riesco, 1 ', ' - ', 'Pista de bolos y petancas y 2 pistas de chito '),
			('IDB Miguel Riesco ', 'C/ Miguel Riesco, 7 ', ' - ', 'Pista de baloncesto '),
			('IDB Miguel Yuste ', 'C/ Miguel Yuste, 64 ', ' - ', 'Pista de fútbol sala y pista de baloncesto '),
			('IDB Minaya ', 'C/ Minaya, 5 ', ' - ', 'Pista de baloncesto '),
			('IDB Mirador de la Reina (Cerro Minguete) ', 'C/ Mirador de la Reina, 2 ', ' - ', 'Campo de fútbol 7 de césped artificial. Pista polideportiva. 2 pistas de tenis. 2 pistas de pádel. 2 tenis de mesa. Pista de bolos y petanca '),
			('IDB Mirasierra ', 'C/ Nuria,83 ', ' - ', 'Pista de baloncesto y pista polideportiva '),
			('IDB Molino', 'Pº. del Molino, 2', ' - ', '2 pistas de bolos y petanca '),
			('IDB Mondariz ', 'Plaza Mondariz, 10 B ', ' - ', 'Pista de fútbol sala y pista de balonmano '),
			('IDB Monóvar ', 'C/ Monóvar, 3 ', ' - ', 'Pista de patinaje '),
			('IDB Montalbos ', 'C/ Montalbos, 14 ', ' - ', 'Pista de patinaje y 3 pistas de chito '),
			('IDB Montecarmelo ', 'C/ Monasterio del Paular, 138 ', ' - ', 'Pista de baloncesto. Campo de fútbol 7 de césped artificial. Pista de fútbol sala '),
			('IDB Montecarmelo McDonald’s ', 'Avda. de Montecarmelo,1 ', ' - ', 'Pista polideportiva '),
			('IDB Mozart ', 'C/ Mozart, frente nº 46 ', ' - ', 'Campo de fútbol sala de tierra '),
			('IDB Nevado del Cumbal ', 'C/ del Nevado del Cumbal, 4 ', ' - ', 'Campo de fútbol 11 de césped artificial (con 2 marcajes de fútbol 7) '),
			('IDB Nicolasa Gómez ', 'C/ Nicolasa Gómez, 1 ', ' - ', 'Pista polideportiva '),
			('IDB Novecento ', 'C/ Novecento, 6', ' - ', '3 pistas de baloncesto '),
			('IDB Nuestra Señora de la Paloma (El Campito) ', 'C/ Carrera de San Francisco, 4 ', ' - ', 'Pista polideportiva '),
			('IDB Nuestra Señora de Loreto ', 'C/ Timón, 16 ', ' - ', 'Pista baloncesto '),
			('IDB Nuestra Señora del Buen Camino – Parque de las Tormentas', 'Glorieta Rio Záncara, 1 ', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB Nueva Esperanza ', 'C/ Virgen de los Desamparados, 12 B ', ' - ', 'Pista de minibaloncesto y pista polideportiva '),
			('IDB Obispo ', 'C/ Palomares, 34 (parque Huerta del Obispo)', ' - ', '2 pistas de baloncesto y pista de patinaje con gradas. '),
			('IDB Ontanilla ', 'C/ Ontanilla, 1 con Avda. de los Poblados, 115 ', ' - ', 'Campo de fútbol 7 de césped artificial '),
			('IDB Orcasur II ', 'Avda. de Orcasur, 53 ', ' - ', 'Pista polideportiva. 2 pistas de baloncesto. 3 pistas voleibol. 4 tenis de mesa. '),
			('IDB Orión – Júpiter ', 'C/ Júpiter, 18 ', ' - ', 'Pista polideportiva y pista de baloncesto con cubierta '),
			('IDB Oyarzun', 'Pza. de Oyarzun, 1 (Poblado Dirigido de Orcasitas)', ' - ', '2 pistas de bolos y petanca '),
			('IDB P.A.R. Avda. Marqués de Corbera ', 'Avda. Marqués de Corbera, 62 ', ' - ', 'Pista de patinaje '),
			('IDB P.A.R. San Lamberto ', 'C/ San Lamberto, 20 ', ' - ', 'Pista de baloncesto '),
			('IDB Pabellón del Cementerio ', 'C/ Pico de la Cierva s/n. ', ' - ', 'Pabellón '),
			('IDB Pablo Casals', 'Pº. de la Ermita del Santo, 10 ', ' - ', 'Pista de fútbol sala '),
			('IDB Pádel – Madrid Las Tablas ', 'Avda. del Camino de Santiago, 25', ' - ', '4 pistas de tenis (2 de ellas de césped artificial). 12 pistas de pádel de cristal (10 de ellas cubiertas) '),
			('IDB Pádel Rio San Pol', 'Pº. Marqués de Monistrol, s/n', ' - ', '6 pistas de pádel '),
			('IDB Padre Damián ', 'C/ Padre Damián, 24', ' - ', '5 pistas de pádel '),
			('IDB Palas del Rey ', 'C/ Palas de Rey,17 ', ' - ', 'Pista polideportiva '),
			('IDB Palomeras Bajas ', 'C/ Puerto Balbarán, 6 ', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB PAR Antonio López ', 'C/ Antonio López, 27-31 ', ' - ', 'Pista polideportiva '),
			('IDB PAR Avda. Rafaela Ibarra ', 'Avda. Rafaela Ibarra, 51 ', ' - ', 'Pista de balonmano '),
			('IDB PAR Castrillo de Aza ', 'Avda. Santa Eugenia, 1. ', ' - ', 'Pista baloncesto '),
			('IDB PAR La Alcazaba ', 'C/ Sinesio Delgado, 26 ', ' - ', 'Pista polideportiva '),
			('IDB PAR Manuel Noya ', 'C/ Manuel Noya, 2 C ', ' - ', 'Pista polideportiva '),
			('IDB PAR Moralzarzal ', 'C/ Moralzarzal, 88 (cubierta PAR Moralzarzal) ', ' - ', 'Pista polideportiva y 2 pistas de bolos y petanca '),
			('IDB PAR Ramón Gómez de la Serna ', 'C/ Ramón Gómez de la Serna, 49 ', ' - ', 'Pista de baloncesto '),
			('IDB Parque Adelfas ', 'C/ Martínez Corrochano, 26 ', ' - ', 'Campo de fútbol 11 de césped artificial. Pista de baloncesto. Pista de pádel de cristal. Tenis de mesa. 2 campos de chito '),
			('IDB Parque Alfredo Kraus ', 'C/ del Mar Adriático, 7 ', ' - ', 'Pista de chito '),
			('IDB Parque Aluche ', 'C/ Valmojado, 4, 6 y 10', ' - ', 'Campo de fútbol 11 de tierra. Campo de fútbol 11 de césped artificial. Pista de fútbol sala. 3 pistas de baloncesto. 7 bolos y petanca. 3 pistas de chito. Tenis de mesa. Circuito de bicicletas '),
			('IDB Parque Antonio Pirala ', 'C/ Antonio Pirala, s/n', ' - ', '2 pistas de baloncesto. Pista de fútbol sala '),
			('IDB Parque Arriaga ', 'Avda. de Daroca, 93 ', ' - ', 'Pista de fútbol sala y 2 pistas de baloncesto '),
			('IDB Parque Arroyo del Fresno ', 'Avda. Ventisquero de la Condesa, 43 ', ' - ', 'Pista polideportiva y pista de baloncesto '),
			('IDB Parque Arroyo Pozuelo I ', 'C/ Arroyo Pozuelo, 10 ', ' - ', 'Pista de baloncesto. Pista de baloncesto 3x3. Pista de fútbol sala. Tenis de mesa '),
			('IDB Parque Atenas', 'Pº. Virgen del Puerto, 3 B c/v Pº de Plasencia ', ' - ', 'Pista de fútbol sala y tenis de mesa '),
			('IDB Parque Boadilla ', 'Ctra. Boadilla del Monte, frente al nº 53 ', ' - ', 'Pista polideportiva. Pista de baloncesto '),
			('IDB Parque Breogán ', 'Avda. de Brasilia, 2 y 4 ', ' - ', 'Pistas de pádel. 2 tenis de mesa. Circuito de footing. Campo de fútbol 7 de césped artificial. Pista de fútbol sala. Pista de baloncesto. '),
			('IDB Parque Briviesca ', 'C/ Briviesca, 4 ', ' - ', 'Pista de baloncesto '),
			('IDB Parque Calle Onil ', 'C/ Navia, 12 ', ' - ', 'Pista de fútbol sala '),
			('IDB Parque Calle Vado ', 'C/ Antonio López, 189 c/v C/ Vado ', ' - ', 'Pista de baloncesto y pista de balonmano '),
			('IDB Parque Caramuel ', 'C/ Caramuel, 53 ', ' - ', 'Pista polideportiva y pista de patinaje '),
			('IDB Parque Central de Ingenieros ', 'C/ La Pícara Molinera, 49', ' - ', '2 pistas de baloncesto'),
			('IDB Parque Cerro Almodóvar I ', 'C/ Los Yébenes, 105 (Parque Cerro Almodóvar)', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB Parque Cerro Almodóvar II', 'Parque Cerro Almodóvar', ' - ', '7 pistas de bolos y petancas. 3 pistas de Chito '),
			('IDB Parque Comillas ', 'C/ Antonio Leyva, 35 ', ' - ', 'Campo de fútbol 7. Pista polideportiva. Pista de fútbol sala. 2 pistas de bolos y petanca. 2 tenis de mesa '),
			('IDB Parque Cuña Verde ', 'Avda. de Daroca ', ' - ', 'Campo de fútbol 11 de tierra. Campo de fútbol 7 de tierra. 2 pistas de baloncesto. Circuito de bicicletas. '),
			('IDB Parque Darwin', 'Frente Avenida de Moratalaz, 58', ' - ', '2 pistas de baloncesto '),
			('IDB Parque de Begoña ', 'Avda. Llano Castellano, 1 ', ' - ', 'Pista de fútbol sala y pista de baloncesto '),
			('IDB Parque de Berlín ', 'C/ Marcenado,51 ', ' - ', 'Pista polideportiva y pista de chito '),
			('IDB Parque de Enrique Herreros', 'Calle Bravo Murillo, 49 ', ' - ', 'Pista de baloncesto'),
			('IDB Parque de Entrevías ', 'Parque de Entrevías', ' - ', 'Pista de patinaje y pista de petanca '),
			('IDB Parque de la Arganzuela (Patinaje)', 'Puente de Praga–Pº de la Chopera, 2 ', ' - ', 'Pista de patinaje y pista de skate '),
			('IDB Parque de la Arganzuela', 'Puente de Praga–Pº de Yeserías, 10 ', ' - ', 'Campo de fútbol 11 de césped artificial y 2 campos fútbol 7 '),
			('IDB Parque de la Cornisa ', 'C/Rosario, 5 ', ' - ', 'Pista de baloncesto. Pista de vóley y futbóley. Pista de bádminton. Tenis de mesa '),
			('IDB Parque de la Ventilla ', 'C/ Vía Límite - Parque de la Ventilla ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. 2 canastas baloncesto 3x3. Pista de patinaje. Pistas de bolos y petanca '),
			('IDB Parque de la Vicalvarada ', 'C/ Vereda del Pinar, 1 ', ' - ', 'Campo de fútbol 11 de césped artificial. Pista de minibaloncesto. Pista de patinaje. Patinódromo. Tenis de mesa. 2 pistas de bolos y petanca. Pista de chito. Campo de fútbol 11 de césped artificial '),
			('IDB Parque de Las Cruces ', 'Avda. de los Poblados s/n (Parque de las Cruces) ', ' - ', 'Pista de baloncesto. Pista de balonmano. Campo de fútbol . 2 campos de fútbol 7 '),
			('IDB Parque de las Cruces I ', 'C/ Rompedizo, 15 ', ' - ', 'Campo de fútbol 11 de tierra. Pista de fútbol sala. Tenis de mesa. Circuito de bicicletas '),
			('IDB Parque de las Cruces II ', 'C/ Vidauba, 3', ' - ', '2 pistas de fútbol sala y tenis mesa '),
			('IDB Parque de los Carneros ', 'C/ Baja de la Iglesia, 36 ', ' - ', 'Pista de baloncesto '),
			('IDB Parque de Manoteras – Vélez Rubio ', 'C/ Bacares, 20 ', ' - ', 'Pista de baloncesto (con equipamiento para 2 baloncestos transversales). Pista de patinaje. 3 tenis de mesa. 2 pistas de calva '),
			('IDB Parque de Olof Palme ', 'C/ Cerecinos, 1 - Parque Olof Palme ', ' - ', 'Pista de skate '),
			('IDB Parque de Santa Adela ', 'C/ Santa Adela, 14 ', ' - ', 'Pista de baloncesto cubierta '),
			('IDB Parque de Santa Eugenia ', 'C/ Zazuar, 12. ', ' - ', 'Pista de skate. Tenis de mesa. Pista de Bolos y petanca. Circuito de vida '),
			('IDB Parque del Cementerio ', 'C/ Montes de Barbanza, 15. ', ' - ', 'Pista polideportiva y pista de fútbol sala '),
			('IDB Parque del Oeste', 'Pº. de Camoens, 10 ', ' - ', 'Pista de baloncesto '),
			('IDB Parque Doña Guiomar I – Gestión indirecta: Sporting de Hortaleza', 'C/ Monovar, 8', ' - ', '2 campos de fútbol 11 de césped artificial (con 2 marcajes de F7 cada uno) '),
			('IDB Parque Doña Guiomar II', 'Ctra. de la Estación de Hortaleza, 7 ', ' - ', '2 pistas de baloncesto 3x3 '),
			('IDB Parque Doña Guiomar III ', 'C/ Monovar, 4', ' - ', 'tenis de mesa '),
			('IDB Parque El Calero ', 'C/ Virgen de Nuria s/n ', ' - ', 'Pista de baloncesto. Rocódromo. Pista de calistenia. 10 pistas de petanca. '),
			('IDB Parque El Cedral ', 'C/ Arturo Soria, 233 ', ' - ', 'Pista de baloncesto '),
			('IDB Parque Enrique Tierno Galván', 'Parque Enrique Tierno Galván', ' - ', 'Circuito de footing '),
			('IDB Parque Estafeta ', 'C/ Estafeta, 2 ', ' - ', 'Pista polideportiva. 2 pistas de baloncesto. Minibaloncesto. 4 tenis de mesa. '),
			('IDB Parque Eugenia de Montijo', 'Parque Eugenia de Montijo s/n', ' - ', 'Campo de fútbol 11. 2 pistas polideportivas. Pista de baloncesto. '),
			('IDB Parque Fluvial Río Manzanares', 'Parque fluvial del río Manzanares (a la altura de avda. Los Rosales 115)', ' - ', 'Patinódromo. '),
			('IDB Parque General García Escámez ', 'C/ General García Escámez, 11.', ' - ', 'Pista de baloncesto '),
			('IDB Parque Huerta de la Salud ', 'C/ del Mar de las Antillas, 10', ' - ', '2 pistas de bolos y petanca. Pista de chito '),
			('IDB Parque Juan Pablo II ', 'Avda. de las Piceas, 13 ', ' - ', 'Campo de rugby de césped artificial. 2 pistas de pádel de cristal '),
			('IDB Parque La Alcazaba ', 'Avda. del Ferrol,34 ', ' - ', 'Pista de fútbol sala y pista de baloncesto '),
			('IDB Parque La Milanera (La Coma) ', 'C/ Ramón Gómez de la Serna, 14 ', ' - ', 'Pista de fútbol sala. 2 pistas de patinaje. Pista de vóley-playa '),
			('IDB Parque la Viña ', 'C/ Concejo de Teverga, 2 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. 2 tenis de mesa '),
			('IDB Parque Lineal del Manzanares ', 'C/ Embajadores, s/n', ' - ', 'Campos de fútbol 11 (uno de tierra y otro césped artificial). Campo de fútbol 7. 2 pistas polideportivas. Circuito de vida '),
			('IDB Parque Luis Buñuel', 'C/ Luis Buñuel frente nº 12 ', ' - ', 'Pista de baloncesto '),
			('IDB Parque Madrid Sur – La Diligencia ', 'C/ La Diligencia, 5 (Parque Madrid Sur) ', ' - ', 'Pista de baloncesto y pista de patinaje '),
			('IDB Parque Manuel Azaña ', 'C/ Jazmín, 51 ', ' - ', 'Pista de baloncesto '),
			('IDB Parque Marchamalo ', 'C/ Marchamalo detrás del nº 15 ', ' - ', 'Pista polideportiva '),
			('IDB Parque Martala II ', 'C/ Pico de los Artilleros, 21 posterior', ' - ', '3 canastas de baloncesto 3x3 '),
			('IDB Parque Meseta ', 'C/ Ronda de las Cooperativas, 6', ' - ', '2 pistas polideportivas. 2 pistas de baloncesto. Pista voleibol. '),
			('IDB Parque Miguel Hernández ', 'C/ Miguel Hernández c/v C/ León Felipe ', ' - ', 'Pista de skate '),
			('IDB Parque Norte ', 'C/ Arzobispo Morcillo, 9 ', ' - ', 'Pista de baloncesto'),
			('IDB Parque Plata y Castañar', 'Pº. Ferroviarios, s/n (parque Plata y Castañar)', ' - ', '3 pistas de fútbol sala/balonmano. 2 pistas de baloncesto. 4 pistas de petanca. 3 pistas de chito. '),
			('IDB Parque Pradolongo ', 'Avda. de los Poblados, 165 (Parque Pradolongo)', ' - ', '2 pistas de baloncesto y circuito de bicicletas '),
			('IDB Parque Rafael Finat ', 'C/ Fuerte de Navidad, 1 ', ' - ', 'Pista de patinaje '),
			('IDB Parque Real de Arganda ', 'C/ Real de Arganda, 45 ', ' - ', 'Pista de fútbol sala '),
			('IDB Parque Roma I ', 'C/ Juan Esplandiú, 4-B ', ' - ', 'Pista polideportiva y pista de fútbol sala '),
			('IDB Parque Roma III ', 'C/ Alcalde Sainz de Baranda, 90', ' - ', 'Rocódromo '),
			('IDB Parque Salvador Madariaga ', 'C/ Salvador de Madariaga, s/n ', ' - ', 'Pista de baloncesto. 2 pistas de ecuavoley. Minifrontón compartida con 1 pista de ecuavoley. '),
			('IDB Parque San Blas ', 'C/ Albaida, Avda. Arcentales, C/ Alberique y C/ Ajofrín', ' - ', '2 pistas de chito y circuito de footing '),
			('IDB Parque San Luciano ', 'C/ Menasalbas, 6 posterior (Parque San Luciano) ', ' - ', 'Pista de fútbol sala. '),
			('IDB Parque Sector Surbatán ', 'C/ Sepúlveda, 206 ', ' - ', 'Pista de patinaje y 2 pistas de bolos y petanca '),
			('IDB Parque Supermanzana 7 ', 'C/ Sangenjo, 17 ', ' - ', 'Pista polideportiva '),
			('IDB Parque Vallecas Villa ', 'C/ Fuentidueña, 8 c/v C/ Puerto Porzuna. ', ' - ', 'Pista polideportiva y pista de skate '),
			('IDB Parque Z ', 'C/ Marroquina, 88 posterior–Parque de Moratalaz ', ' - ', 'Pista de patinaje y 2 tenis de mesa '),
			('IDB Parroquia Santa Eugenia ', 'C/ Virgen de las Viñas, 15. ', ' - ', 'Pista de fútbol sala '),
			('IDB Paseo de La Vaguada', 'Pº. de la Vaguada,13', ' - ', '3 pistas de bolos y petanca y pista de chito '),
			('IDB Patrimonio de la Humanidad I ', 'C/ Patrimonio de la Humanidad, 37 ', ' - ', 'Pista de fútbol sala '),
			('IDB Patrimonio de la Humanidad II ', 'C/ Patrimonio de la Humanidad, 27', ' - ', '2 pistas de bolos y petanca. Pista de chito '),
			('IDB Patrimonio de la Humanidad III ', 'C/ Patrimonio de la Humanidad nº 17 ', ' - ', 'Pista de patinaje '),
			('IDB Pavones Este “Lilí Álvarez” ', 'C/ Cañón del Río Lobo, 8 ', ' - ', 'Campo de fútbol 11 de césped artificial. Campo de fútbol 7 de césped artificial. Pista de baloncesto. 4 pistas de pádel. Pista de vóley playa '),
			('IDB Pedro Escudero–Gestión indirecta', 'C/ Pedro Escudero, esq. Avda. de Palomeras  ', ' - ', 'Pista fútbol sala y pista Baloncesto'),
			('IDB Pedro Yagüe ', 'C/ Pedro Yagüe, 11 (P.A.R.) ', ' - ', 'Pista polideportiva '),
			('IDB Peonías – José Miguel Vicens ', 'C/ de las Peonías, 2 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto '),
			('IDB Petanca Marqués de Monistrol', 'Pº. Marqués de Monistrol, s/n', ' - ', '2 pistas de bolos y petanca '),
			('IDB Petanca Parque de Fuencarral ', 'C/ Afueras a Valverde, 2 ', ' - ', 'Pista de bolos y petanca '),
			('IDB Piedrahita ', 'C/ Piedrahita, 34 c/v Real Madrid ', ' - ', 'Pista de baloncesto '),
			('IDB Pinar de La Elipa ', 'Parque de La Elipa ', ' - ', 'Pista de patinaje '),
			('IDB Pinos de Osuna ', 'C/ Pinos de Osuna, 1 ', ' - ', 'Pista de fútbol sala '),
			('IDB Piqueñas ', 'C/ Pinar de San José, 72 con c/ La Torla', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB Pirineos ', 'C/ Pirineos frente a nº 7', ' - ', '2 pistas de baloncesto 3x3 '),
			('IDB Pista de Patinaje ', 'C/ Puerto Porzuna s/n. ', ' - ', 'Pista de patinaje '),
			('IDB Plan Parcial ', 'C/ Plan Parcial, 3 ', ' - ', 'Pista polideportiva '),
			('IDB Playa Bolnuevo ', 'C/ Playa de Bolnuevo, 1 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. Pista de voleibol. Pista de bolos y petanca '),
			('IDB Plaza Arteijo', 'Pza. de Arteijo, 10 B ', ' - ', '2 pistas de baloncesto '),
			('IDB Plaza Arturo Barea', 'Pza. Arturo Barea', ' - ', 'Rocódromo y tenis de mesa '),
			('IDB Plaza Colonia Oroquieta', 'Av. Andalucía c/v Ctra. Villaverde a Vallecas (parque Plaza Chozas de Canales) ', ' - ', 'Pista de baloncesto '),
			('IDB Plaza de Bami-Benidorm ', 'C/ José Villena c/v C/ Benidorm ', ' - ', 'Pista de baloncesto '),
			('IDB Plaza de María Soledad Torres Acosta', 'Plaza de María Soledad Torres Acosta', ' - ', 'Pista de Street workout y parkour '),
			('IDB Plaza de Sestao', 'Pza. de Sestao, 1 (Poblado Dirigido de Orcasitas) ', ' - ', 'Pista de patinaje '),
			('IDB Plaza del Campillo del Mundo Nuevo', 'Pza. Campillo del Mundo Nuevo s/n ', ' - ', 'Pista de patinaje y pista de Street workout '),
			('IDB Plaza Orotava', 'Pza. Orotava, 1 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. '),
			('IDB Plaza Vallandes ', 'C/ Calesas, 4 ', ' - ', 'Pista de baloncesto. 2 pistas de bolos y petanca. '),
			('IDB Plazas de Ribadeo y Verín', 'Pza. de Verín, 8B ', ' - ', 'Pista polideportiva y pista de baloncesto '),
			('IDB Poblado de Santa Ana ', 'C/ Braille, 15 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. Instalación para deportes sobre ruedas. Pista de baloncesto 3x3 '),
			('IDB Poblado Dirigido ', 'C/ Olesa de Monserrat, 1 ', ' - ', 'Pista de fútbol sala y 2 pistas de baloncesto '),
			('IDB Poblado Dirigido La Elipa ', 'C/ María Teresa Sáez de Heredia, 4 posterior ', ' - ', 'Pista de baloncesto '),
			('IDB Pobladura del Valle ', 'C/ Pobladura del Valle, 11', ' - ', '2 pistas de baloncesto 3x3 '),
			('IDB Poeta Esteban de Villegas ', 'C/ Poeta Esteban de Villegas, 4 ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. Pista de patinaje '),
			('IDB Polígono 20 – Padre Claret ', 'C/ Padre Claret, 18', ' - ', '3 pistas de fútbol sala '),
			('IDB Polígono de África ', 'C/ Villasilos, 1 ', ' - ', 'Campo de fútbol 7 de tierra '),
			('IDB Polígono de las Rosas ', 'C/ Helsinki, 6', ' - ', '2 pistas polideportivas '),
			('IDB Poza de la Sal ', 'C/ Poza de la Sal, 2. ', ' - ', 'Pista de baloncesto '),
			('IDB Pueblo Nuevo ', 'C/ Ascao c/v C/ Luis Ruiz ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. Pista de baloncesto 3x3 '),
			('IDB Puente de Praga ', 'C/ San David s/n ', ' - ', 'Pista de tenis y 7 pistas de pádel. '),
			('IDB Puente de Ventas ', 'C/ Virgen de la Paz, 7 y 9 ', ' - ', 'Pista polideportiva '),
			('IDB Puentelarra ', 'C/ Puentelarra, 12-16', ' - ', '2 pistas de baloncesto 3x3 '),
			('IDB Puerta Bonita ', 'C/ General Ricardos, 166 ', ' - ', 'Campo de fútbol 11 '),
			('IDB Puerto Balbarán ', 'C/ Puerto Balbarán, 4 y 8 ', ' - ', 'Pista de baloncesto y pista de voleibol '),
			('IDB Puerto Corlite ', 'C/ Puerto Corlite, 7 ', ' - ', 'Pista de Minipitch '),
			('IDB Puerto Costabona Tenis– Gestión indirecta ', 'C/ Puerto Velate, 18', ' - ', '6 pistas de tenis y Tenis de mesa '),
			('IDB Puerto de Béjar ', 'C/ Puerto de Béjar, 7 ', ' - ', 'Pista de fútbol sala '),
			('IDB Puerto de Costabona ', 'C/ Puerto Costabona, 7 ', ' - ', 'Pista de fútbol sala '),
			('IDB Puerto Lumbreras ', 'C/ Puerto Lumbreras, 14. ', ' - ', 'Pista de baloncesto '),
			('IDB Puerto Monasterio ', 'C/ Puerto Monasterio, 17', ' - ', '2 pistas de baloncesto '),
			('IDB Puerto Rico – C.D. Alzola ', 'C/ Gainza, 20 ', ' - ', 'Campo de fútbol 11 de tierra'),
			('IDB Puerto Rico ', 'C/ Puerto Rico,54 ', ' - ', '2 pistas de baloncesto '),
			('IDB Puerto Velate ', 'C/ Puerto Velate, 9 ', ' - ', 'Pista de fútbol sala de tierra '),
			('IDB Quinta de los Molinos ', 'C/ Alcalá, 535 c/v Avda. 25 de Septiembre ', ' - ', 'Pista de Atletismo. Pista de baloncesto. Pista de skate '),
			('IDB Quinta de los Molinos II ', 'C/ Iquitos c/v C/ Alcalá, 525 ', ' - ', 'Campo de fútbol 7. Pista polideportiva. 2 pistas de tenis. Pista de minitenis. 3 pistas de pádel (2 de ellas de cristal). Zona de aproach y bunker. 12 puestos de prácticas de golf '),
			('IDB Ramírez de Prado ', 'C/ Ramírez de Prado, 2 ', ' - ', 'Pista de baloncesto y pista de patinaje '),
			('IDB Ramón Gómez de la Serna ', 'C/ Ramón Gómez de la Serna, 22 ', ' - ', 'Campo de fútbol 11 y campo de minipitch '),
			('IDB Ramón Pérez de Ayala ', 'C/ Ramón Pérez de Ayala, 80 B ', ' - ', 'Pista de baloncesto. 2 pistas de fútbol sala. 2 tenis de mesa '),
			('IDB Rancho del Cordobés ', 'C/ Pinsapo, 3 y 4', ' - ', '2 campos de fútbol 7 de tierra y 2 pistas de baloncesto '),
			('IDB Recinto Ferial San Antonio de La Florida', 'Glorieta de San Antonio de la Florida, 8 ', ' - ', 'Pista polideportiva '),
			('IDB Ría Parque Juan Carlos I– Gestión indirecta. Acceso controlado', 'Parque Juan Carlos I', ' - ', 'Lámina de agua para las actividades de piragüismo y kayak polo. Deporte adaptado '),
			('IDB Ricardo Damas ', 'C/ Ricardo Damas, 4 ', ' - ', 'Pista de fútbol sala '),
			('IDB Roc-30 ', 'Avda. de Manzanares, 108', ' - ', 'Rocódromo. '),
			('IDB Rocódromo Villa de Vallecas ', 'Avda. de la Gavia c/v C/Congosto.', ' - ', 'Rocódromo '),
			('IDB Rodríguez Sahagún– Gestión indirecta ', 'C/ Vía Límite- Parque de la Ventilla ', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB Rodríguez Sahagún I ', 'C/ Capitán Blanco Argibay, 173', ' - ', '4 pistas polideportivas. Pista de fútbol sala . 3 pistas de baloncesto '),
			('IDB Rodríguez Sahagún II ', 'C/ Sinesio Delgado, 30 -Pº de la Dirección, 295', ' - ', '2 pistas de fútbol sala. 2 pistas de baloncesto. Pista de patinaje. 2 pistas de bolos y petanca '),
			('IDB Rosa Jardón ', 'C/ Rosa Jardón, 11 ', ' - ', 'Pista de fútbol sala '),
			('IDB Sáez de Oiza – Félix Rodríguez de la Fuente ', 'C/ Félix Rodríguez de la Fuente, 13 posterior ', ' - ', 'Pista de fútbol sala '),
			('IDB Sala Municipal de Esgrima ', 'Avda. Islas Filipinas, 7 ', ' - ', '16 pistas de esgrima '),
			('IDB San Anselmo ', 'C/ San Anselmo, 22 c/v C/ Venta del Pájaro, 26 ', ' - ', 'Pista de baloncesto '),
			('IDB San Aureliano ', 'C/ San Aureliano, 9 y 11 (sobre cubierta de aparcamiento de residentes) ', ' - ', 'Pista de minibaloncesto '),
			('IDB San Benigno ', 'C/ San Benigno, 3 ', ' - ', 'Pista polideportiva '),
			('IDB San Cristóbal de los Ángeles II ', 'C/ Godella, 48 B', ' - ', 'Patinódromo. '),
			('IDB San Cristóbal de los Ángeles III ', 'C/ Moncada, 123', ' - ', 'Frontón y 4 minifrontones o trinquetes '),
			('IDB San Federico ', 'C/ Alcalde Martín de Alzaga, 4 ', ' - ', 'Campo de fútbol 11 '),
			('IDB San Juan Bautista ', 'C/ Agastia, c/v Cidamón ', ' - ', 'Pista polideportiva '),
			('IDB San Lamberto –Gestión indirecta Autorización demanial ', 'C/ San Lamberto s/n', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB San Martín de Porres', 'Pº. Ermita del Santo s/n (Parque de San Isidro) ', ' - ', 'Campo de fútbol 11 '),
			('IDB San Pascual ', 'C/ Esteban Mora esq. Derechos Humanos ', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB San Pol de Mar', 'Pº. San Pol de Mar, 11 ', ' - ', 'Pista de baloncesto '),
			('IDB Sanchinarro I ', 'C/ de la Infanta Catalina Micaela, 33 ', ' - ', 'Pista polideportiva '),
			('IDB Sanchinarro II ', 'C/ de la Infanta Catalina Micaela, 23 ', ' - ', 'Pista polideportiva '),
			('IDB Sanchinarro III ', 'C/ María Tudor, 10 B ', ' - ', 'Pista polideportiva '),
			('IDB Sanchinarro IV ', 'Avda. de Niceto Alcalá Zamora, 12 ', ' - ', 'Pista de skate '),
			('IDB Sanchorreja ', 'C/ Sanchorreja, 8 ', ' - ', 'Campo de fútbol 7 de tierra. Pista polideportiva '),
			('IDB Sangenjo ', 'C/ Sangenjo, 42 ', ' - ', 'Pista de baloncesto '),
			('IDB Santa Ana II', 'Pº. de las Alamedillas, 2 ', ' - ', 'Campo de fútbol 11 y pista de atletismo '),
			('IDB Santa Eugenia ', 'C/ Cerro de Almodóvar, 11 ', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB Santa Hortensia ', 'C/ Santa Hortensia, 34 ', ' - ', 'Pista de fútbol sala y pista de baloncesto '),
			('IDB Santa Marca ', 'C/ Pradillo, 23 ', ' - ', 'Pista de fútbol sala'),
			('IDB Santa Petronila ', 'C/ Santa Petronila, 21 (parque de la Amistad) ', ' - ', 'Pista polideportiva. Pista de baloncesto con gradas. 6 pistas de petanca '),
			('IDB Santa Rita ', 'C/ Alba de Tormes, 2 ', ' - ', 'Campo de fútbol 11 '),
			('IDB Santa Virgilia ', 'C/ Santa Virgilia, 17 posterior ', ' - ', 'Pista polideportiva '),
			('IDB Santuario de Valverde (Montecarmelo)', 'Av. Santuario de Valverde, 41 ', ' - ', 'Pista de baloncesto y pista de patinaje'),
			('IDB Sepúlveda ', 'C/ Sepúlveda, 220 ', ' - ', 'Pista de fútbol sala. Pista polideportiva (baloncesto, tenis y voleibol). Pista de patinaje. Circuito de bicicletas '),
			('IDB Seseña ', 'C/ Seseña, 2 A', ' - ', '11 pistas de calva '),
			('IDB Sierra del Valle ', 'C/ Arroyo del Olivar, 96 ', ' - ', 'Pista de patinaje '),
			('IDB Sierra Elvira ', 'C/ Sierra Elvira, 37 ', ' - ', 'Pista balonmano '),
			('IDB Sinesio Delgado ', 'C/ Isla de Oza, 61 ', ' - ', 'Pista de fútbol sala. Pista de voleibol. 2 pistas de patinaje. Tenis de mesa '),
			('IDB Skate ', 'C/ Capitán Blanco Argibay frente nº 173 ', ' - ', 'Pista de skate '),
			('IDB Skate El Espinillo ', 'C/ Unanimidad s/n –frente al número 40)', ' - ', 'Patinódromo. '),
			('IDB Skate Plaza de los Metales ', 'Pza. Metales c/v cl. Hulla s/n', ' - ', 'Patinódromo. '),
			('IDB Soto Hidalgo ', 'C/ Riaño, 1 A ', ' - ', 'Pista de fútbol sala y pista de baloncesto '),
			('IDB Tapia Fútbol tierra ', 'Avda. Doctor García Tapia, 113 ', ' - ', 'Campo de fútbol 11 de tierra '),
			('IDB Telémaco ', 'C/ Telémaco, 6 (posterior)', ' - ', '2 pistas de baloncesto 3x3'),
			('IDB Tercio Terol ', 'C/ Tulga, 2 con c/ Chindasvinto ', ' - ', 'Pista de baloncesto '),
			('IDB Torrelaguna ', 'C/ Torrelaguna, 123 ', ' - ', 'Pista de baloncesto '),
			('IDB Torrespaña ', 'C/ Sainz de Baranda, 94 ', ' - ', 'Sala de musculación. 3 salas multiusos. Campo de fútbol 7 de césped artificial. 2 pistas polideportivas. Pista de tenis. 3 pistas de pádel de cristal. Circuito de vida. Circuito de bicicleta'),
			('IDB Tres Olivos I Pádel ', 'C/ Cuevas de Montesinos, 27', ' - ', '7 pistas de pádel (1 de cristal) '),
			('IDB Tres Olivos II ', 'Avda. Campo Calatrava, 3 ', ' - ', 'Campo de Rugby '),
			('IDB Tribaldos ', 'C/ Tribaldos, 37 (junto Iglesia)', ' - ', '2 pistas de baloncesto. Circuito de bicicletas. Circuito de vida '),
			('IDB Tribaldos II ', 'C/ Tribaldos, 34 ', ' - ', 'Pista de patinaje '),
			('IDB Trinquete ', 'C/ del Velacho Bajo, 3 ', ' - ', 'Campo de fútbol 11 de tierra '),
			('IDB Urbanización Arroyo del Santo ', 'Avda. de los Prunos, 100 ', ' - ', 'Pista polideportiva y pista de baloncesto '),
			('IDB UVA de Vallecas ', 'C/ Monte de Montjuic, 9. ', ' - ', 'Pista polideportiva y tenis de mesa '),
			('IDB UVA Pan Bendito ', 'C/ Belzunegui s/n', ' - ', '3 pistas polideportivas '),
			('IDB Valdelasierra ', 'C/ Valdelasierra, 7-9 ', ' - ', 'Pista polideportiva '),
			('IDB Valderribas ', 'Avda. Gran Vía del Este, 14 ', ' - ', 'Pista de baloncesto '),
			('IDB Valderromán ', 'C/ Valderromán, 22 (Sobre P.A.R.) ', ' - ', 'Pista de fútbol sala. Pista de baloncesto. Tenis de mesa '),
			('IDB Valdetorres ', 'C/ Valdetorres del Jarama, 29 ', ' - ', 'Pista polideportiva '),
			('IDB Valdeyeros', 'C/ Rosalía de Castro, 77 ', ' - ', 'Campo de fútbol 11 de césped artificial. Campo de fútbol 7 de césped artificial. Pista polideportiva '),
			('IDB Valle Inclán ', 'C/ Valle Inclán, 68 ', ' - ', 'Pista de fútbol sala y pista de patinaje'),
			('IDB Vereda de Ganapanes ', 'C/ Becerrea, 4', ' - ', '2 campos de fútbol 11 (uno de ellos de césped artificial). Pista de fútbol sala de césped artificial. 2 tenis de mesa. Campo de minipitch '),
			('IDB Vía Lusitana ', 'Avda. Vía Lusitana, 19 (Parque Sur)', ' - ', '2 campos de fútbol 11de césped artificial. Pista de fútbol sala. Pista de baloncesto.'),
			('IDB Vicente Quesada ', 'C/ Vicente Quesada, 4 (Parque de San Isidro) ', ' - ', 'Pista de baloncesto '),
			('IDB Villa de Pons - Avenida de San Luis ', 'Avda. de San Luis, 23 B ', ' - ', 'Pista de baloncesto cubierta. 2 tenis de mesa '),
			('IDB Villabona ', 'C/ Villabona, 4 ', ' - ', 'Pista de baloncesto '),
			('IDB Villalonso ', 'C/ Villalonso, 6 y 8 ', ' - ', 'Pista polideportiva '),
			('IDB Virgen de la Estrella', ' Plazuela Virgen de la Estrella, 1 ', ' - ', 'Pista de baloncesto'),
			('IDB Virgen de la Torre ', 'C/ Puerto de Reinosa, 2', ' - ', 'Campos de fútbol 11 de césped artificial y campo de fútbol 7 de tierra '),
			('IDB Virgen del Cortijo ', 'C/ Oña, 18 ', ' - ', 'Campo de fútbol 11 de tierra (con 2 marcajes de F7) '),
			('IDB Vital Aza ', 'C/ Vital Aza esq. C/ Ezequiel Solana ', ' - ', 'Pista de baloncesto'),
			('IDB Marquesa de Amboage ', 'C/ Bueso Pineda, 4 ', ' - ', 'Pista polideportiva '),
			('IDB Vivero de La Pilarica ', 'C/ Vivero de la Pilarica, 3', ' - ', '3 pistas polideportivas '),
			('IDB Yeserías', 'Pº. de Yeserías, 5', ' - ', 'Frontón corto y campo de chito '),
			('IDB Yesero ', 'C/ del Yesero, 1 ', ' - ', 'Pista fútbol sala '),
			('IDB Zazuar. ', 'C/ Zazuar, 1 ', ' - ', 'Pista de baloncesto '),
			('IDB Zofío ', 'C/ Ricardo Beltrán y Rózpide, 12 ', ' - ', 'Campo de fútbol 11 de césped artificial '),
			('IDB Zofío II', 'C/ Ricardo Beltrán y Rózpide, 16', ' - ', 'Frontón corto '),
			('Parque Lineal UZI 0.06 Arroyofresno ', 'C/ María de Maeztu, s/n ', ' - ', 'Pista de baloncesto'),
			('Pista Básica Jardines del Teniente Alcalde', 'Jardines del Teniente Alcalde Pérez Pillado en. C/ de Lucio del Valle ', ' - ', 'Pista polideportiva. Pista hockey. Área multideportiva infantil '),
			('Pista de patinaje Paco de Lucía', 'Parque Paco de Lucía ', ' - ', 'Pista de patinaje'),
			('Pista de Petanca Centro de Mayores La Vaguada ', 'C/ Monforte de Lemos, 36', ' - ', '2 pistas de petanca');


			INSERT INTO users (username, first_name, family_name, email, hashed_pwd, gender, birth, u_level, pref_sports)
			VALUES ('Frankl89', 'Francisco', 'Sánchez', 'fran_sanchez@yo.com', 'ksjaoa895j9', 'Hombre', '01/03/1989', 'Intermedio', ARRAY ['baloncesto', 'fútbol', 'fútbol 7']::sports[]),
			('Emmy83', 'Emma', 'Martínez', 'emmy83@gmail.com', 'sakx02nsoaj', 'Mujer', '15/01/1983', 'Básico', ARRAY ['baloncesto', '3x3', 'fútbol 7']::sports[]),
			('AnaIsabel', 'Ana Isabel', 'Martínez', 'anai@yo.com', 'sj192jh9saks', 'Mujer', '22/09/1990', 'Intermedio', ARRAY ['baloncesto', 'fútbol', 'fútbol 7']::sports[]),
			('Tiatula49', 'María del Mar', 'Pérez', 'mmar.perez@yahoo.es', 's1kshb9aakj3', 'Mujer', '23/10/1994', 'Intermedio', ARRAY ['baloncesto', '3x3', 'fútbol 7']::sports[]),
			('Estheruki', 'Esther', 'Marzo', 'est_mar@gmail.com', 'kksu40kb026', 'Mujer', '07/07/1989', 'Competición', ARRAY ['fútbol', 'fútbol sala']::sports[]),
			('Karlitox', 'Carlos', 'Romero', 'cromero@yahoo.es', 'aku4kIlsig54', 'Hombre', '11/12/1998', 'Básico', ARRAY ['baloncesto', '3x3', 'fútbol 7']::sports[]),
			('ErRamonchu', 'Ramón', 'Fernández', 'rfernadez@yo.com', 'a92jg9basubk', 'Hombre', '10/02/1991', 'Competición', ARRAY ['baloncesto', '3x3', 'fútbol 7']::sports[]);

			INSERT INTO games (created_by, g_date, g_time, g_level, g_gender, created_at, updated_at, adapted, notes, participants)
			VALUES ('Estheruki', '2021-12-19', '16:30:00', 'Básico', 'Mixto', '2021/11/05 11:03:57', '2021/11/06 17:03:17', false, '', '{Romualdo,Karlitox,erRamonchu}'),
			('Karlitox', '2021-12-20', '17:00:00', 'Intermedio', 'Masculino', '2021/11/06 11:03:57', '2021/11/07 17:03:17', true, 'Se apuntan dos colegas en silla de ruedas', '{Karlitox,erRamonchu}'),
			('ErRamonchu', '2021-12-20', '20:00:00', 'Competición', 'Mixto', '2021/11/07 11:03:57', '2021/11/08 17:03:17', false, '', '{Karlitox,erRamonchu,EstherKS}'),
			('Estheruki', '2021-12-22', '12:00:00', 'Básico', 'Femenino', '2021/11/08 11:03:57', '2021/11/09 17:03:17', false, '', '{Karlitox,erRamonchu}'),
			('Karlitox', '2021-12-22', '17:30:00', 'Intermedio', 'Masculino', '2021/11/09 11:03:57', '2021/11/10 17:03:17', false, '', '{Palman78, Karlitox,erRamonchu}'),
			('ErRamonchu', '2021-12-23', '20:00:00', 'Competición', 'Masculino', '2021/11/10 11:03:57', '2021/11/10 17:03:17', false, '', '{Karlitox,erRamonchu}')
			`);
		console.info("Insertion successful! 🚀");
	} catch (error) {
		console.info("Insertion failed! ❌", error.message);
	}
};

seed();
